import { redirect } from "next/navigation";
import { hasAppUsers } from "@/server/auth/identity-service";
import { loginAction } from "../admin/identity-actions";

export const dynamic = "force-dynamic";

export default async function LoginPage({ searchParams }: { searchParams: Promise<{ error?: string; loggedOut?: string }> }) {
  if (!(await hasAppUsers())) redirect("/setup");
  const query = await searchParams;
  return <main className="grid min-h-screen place-items-center bg-[var(--background)] p-4 text-[var(--foreground)]"><section className="w-full max-w-md rounded-2xl border border-[var(--border)] bg-[var(--surface)] p-6 shadow-[var(--shadow-card)]"><p className="text-xs font-black uppercase tracking-[0.16em] text-[var(--muted)]">OCRCraft</p><h1 className="mt-2 text-2xl font-black">Anmelden</h1><p className="mt-2 text-sm leading-6 text-[var(--muted)]">Melde dich mit E-Mail oder Username und Passwort an. Der Vereinscode kann als lokaler Zugang verwendet werden.</p>{query.error ? <p aria-live="assertive" className="mt-4 rounded-xl border border-[var(--danger)] bg-[var(--danger-bg)] p-3 text-sm font-bold text-[var(--danger)]">Anmeldung fehlgeschlagen. Prüfe Zugangsdaten und Vereinscode.</p> : null}{query.loggedOut ? <p aria-live="polite" className="mt-4 rounded-xl border border-[var(--success-border)] bg-[var(--success-bg)] p-3 text-sm font-bold text-[var(--success-foreground)]">Du wurdest abgemeldet.</p> : null}<form action={loginAction} className="mt-5 grid gap-4"><label className="grid gap-1 text-sm font-bold" htmlFor="identity">E-Mail oder Username<input autoComplete="username" className="min-h-11 rounded-lg border border-[var(--border)] bg-[var(--surface-subtle)] px-3 font-normal" id="identity" name="identity" required /></label><label className="grid gap-1 text-sm font-bold" htmlFor="password">Passwort<input autoComplete="current-password" className="min-h-11 rounded-lg border border-[var(--border)] bg-[var(--surface-subtle)] px-3 font-normal" id="password" minLength={8} name="password" type="password" /></label><label className="grid gap-1 text-sm font-bold" htmlFor="code">Vereinscode<span className="text-xs font-normal text-[var(--muted)]">Alternativ zum Passwort.</span><input autoComplete="one-time-code" className="min-h-11 rounded-lg border border-[var(--border)] bg-[var(--surface-subtle)] px-3 font-normal" id="code" name="code" type="password" /></label><button className="min-h-11 rounded-lg bg-[var(--control-strong)] px-4 text-sm font-black text-[var(--control-strong-foreground)]" type="submit">Anmelden</button></form></section></main>;
}
