import "server-only";
import { z } from "zod";
import { ensureDatabaseReady } from "@/server/db/database-ready";
import { withDuckDbConnection, withDuckDbReadConnection } from "@/server/db/duckdb";
export type AppTaskStatus = "queued"|"running"|"succeeded"|"failed"|"cancelled";
export type AppTaskType = "duplicate_scan"|"duplicate_resolve"|"search_rebuild";
export const duplicateResolutionSchema = z.object({
  taskId: z.string().uuid(),
  leftExerciseId: z.string().uuid(),
  rightExerciseId: z.string().uuid(),
  decision: z.enum(["left", "right", "both", "ignored"]),
});
export const duplicateResolutionPayloadSchema = z.object({ resolutions: z.array(duplicateResolutionSchema).min(1) });
export type DuplicateResolutionPayload = z.infer<typeof duplicateResolutionPayloadSchema>;
export interface AppTask { readonly id:string; readonly taskType:AppTaskType; readonly title:string; readonly status:AppTaskStatus; readonly progress:number; readonly progressMessage:string|null; readonly errorMessage:string|null; readonly createdAt:string; readonly startedAt:string|null; readonly finishedAt:string|null; readonly payload:unknown; }
export interface AppTaskSummary { readonly queued:number; readonly running:number; readonly failed:number; }
export interface QueueIssue { readonly id:string; readonly title:string; readonly status:string; readonly progress:number; readonly message:string|null; readonly createdAt:string; readonly source:"task"|"media"; }
export async function enqueueAppTask(input:{type:AppTaskType;title:string;requestedBy?:string|null;payload?:unknown}):Promise<string>{await ensureDatabaseReady();return withDuckDbConnection(async c=>{const r=await c.runAndReadAll("INSERT INTO app_task_queue(task_type,title,payload_json,requested_by) VALUES ($type,$title,$payload,$requestedBy::UUID) RETURNING id::VARCHAR",{type:input.type,title:input.title,payload:JSON.stringify(input.payload??{}),requestedBy:input.requestedBy??null});return String(r.getRows()[0]?.[0]);});}
export async function getAppTaskSummary():Promise<AppTaskSummary>{await ensureDatabaseReady();return withDuckDbReadConnection(async c=>{const r=(await c.runAndReadAll("SELECT (SELECT count(*) FILTER (WHERE status='queued') FROM app_task_queue)+(SELECT count(*) FILTER (WHERE status='queued') FROM exercise_image_generation_jobs),(SELECT count(*) FILTER (WHERE status='running') FROM app_task_queue)+(SELECT count(*) FILTER (WHERE status='running') FROM exercise_image_generation_jobs),(SELECT count(*) FILTER (WHERE status='failed') FROM app_task_queue)+(SELECT count(*) FILTER (WHERE status='failed' AND created_at >= current_timestamp - INTERVAL '24 hours') FROM exercise_image_generation_jobs)")).getRows()[0]??[];return{queued:Number(r[0]??0),running:Number(r[1]??0),failed:Number(r[2]??0)};});}
export async function listAppTasks(limit=50):Promise<readonly AppTask[]>{await ensureDatabaseReady();try{return await withDuckDbReadConnection(async c=>{const r=await c.runAndReadAll("SELECT id::VARCHAR,task_type,title,status,progress,progress_message,error_message,created_at,started_at,finished_at,payload_json FROM app_task_queue ORDER BY created_at DESC LIMIT $limit",{limit:Math.max(1,Math.min(200,limit))});return r.getRows().map(x=>({id:String(x[0]),taskType:String(x[1]) as AppTaskType,title:String(x[2]),status:String(x[3]) as AppTaskStatus,progress:Number(x[4]??0),progressMessage:x[5]==null?null:String(x[5]),errorMessage:x[6]==null?null:String(x[6]),createdAt:String(x[7]),startedAt:x[8]==null?null:String(x[8]),finishedAt:x[9]==null?null:String(x[9]),payload:JSON.parse(String(x[10]??"{}"))}));});}catch(error){if(error instanceof Error&&error.message.includes("Timed out waiting for DuckDB write lock"))return [];throw error;}}
export async function listQueueIssues(limit=20):Promise<readonly QueueIssue[]>{await ensureDatabaseReady();try{return await withDuckDbReadConnection(async c=>{const r=await c.runAndReadAll("SELECT id::VARCHAR,title,status,progress,COALESCE(error_message,progress_message),created_at,'task' FROM app_task_queue UNION ALL SELECT j.id::VARCHAR,COALESCE(t.name,e.canonical_name),'media:'||j.status,CASE WHEN j.status='succeeded' THEN 100 WHEN j.status='running' THEN 50 ELSE 0 END,j.error_message,j.created_at,'media' FROM exercise_image_generation_jobs j JOIN exercises e ON e.id=j.exercise_id LEFT JOIN exercise_translations t ON t.exercise_id=e.id AND t.locale='de' WHERE j.status IN ('queued','running','failed') ORDER BY created_at DESC LIMIT $limit",{limit:Math.max(1,Math.min(100,limit))});return r.getRows().map(x=>({id:String(x[0]),title:String(x[1]),status:String(x[2]),progress:Number(x[3]??0),message:x[4]==null?null:String(x[4]),createdAt:String(x[5]),source:String(x[6]) as "task"|"media"}));});}catch(error){if(error instanceof Error&&error.message.includes("Timed out waiting for DuckDB write lock"))return [];throw error;}}
export async function claimNextAppTask():Promise<AppTask|null>{await ensureDatabaseReady();return withDuckDbConnection(async c=>{const r=await c.runAndReadAll("UPDATE app_task_queue SET status='running',started_at=current_timestamp,updated_at=current_timestamp,progress=1,progress_message='Wird ausgeführt' WHERE id=(SELECT id FROM app_task_queue WHERE status='queued' ORDER BY created_at,id LIMIT 1) AND status='queued' RETURNING id::VARCHAR,task_type,title,progress,progress_message,created_at,started_at,payload_json");const x=r.getRows()[0];return x?{id:String(x[0]),taskType:String(x[1]) as AppTaskType,title:String(x[2]),status:'running',progress:Number(x[3]??1),progressMessage:String(x[4]),errorMessage:null,createdAt:String(x[5]),startedAt:String(x[6]),finishedAt:null,payload:JSON.parse(String(x[7]??"{}"))}:null;});}
export async function updateAppTaskProgress(id:string, progress:number, message:string):Promise<void>{await ensureDatabaseReady();await withDuckDbConnection(c=>c.run("UPDATE app_task_queue SET progress=$progress,progress_message=$message,updated_at=current_timestamp WHERE id=$id::UUID AND status='running'",{id,progress:Math.max(1,Math.min(99,Math.trunc(progress))),message}));}
export async function finishAppTask(id:string,status:Exclude<AppTaskStatus,"queued"|"running">,errorMessage?:string):Promise<void>{await ensureDatabaseReady();await withDuckDbConnection(c=>c.run("UPDATE app_task_queue SET status=$status,progress=$progress,progress_message=$message,error_message=$error,finished_at=current_timestamp,updated_at=current_timestamp WHERE id=$id::UUID AND status='running'",{id,status,progress:status==='succeeded'?100:0,message:status==='succeeded'?'Abgeschlossen':status==='cancelled'?'Abgebrochen':'Fehlgeschlagen',error:errorMessage?.slice(0,2000)??null}));}
export async function cancelAppTask(id:string):Promise<void>{await ensureDatabaseReady();await withDuckDbConnection(c=>c.run("UPDATE app_task_queue SET status='cancelled',finished_at=current_timestamp,updated_at=current_timestamp,progress_message='Abgebrochen' WHERE id=$id::UUID AND status IN ('queued','running')",{id}));}
export async function retryAppTask(id:string):Promise<void>{await ensureDatabaseReady();await withDuckDbConnection(c=>c.run("UPDATE app_task_queue SET status='queued',started_at=NULL,finished_at=NULL,error_message=NULL,progress=0,progress_message='Erneut eingeplant',updated_at=current_timestamp WHERE id=$id::UUID AND status IN ('failed','cancelled')",{id}));}
export async function deleteAppTask(id:string):Promise<void>{await ensureDatabaseReady();await withDuckDbConnection(c=>c.run("DELETE FROM app_task_queue WHERE id=$id::UUID AND status IN ('succeeded','failed','cancelled')",{id}));}
