BEGIN TRANSACTION;

CREATE TABLE exercise_obstacle_guidance (
  exercise_id UUID NOT NULL REFERENCES exercises(id),
  locale VARCHAR NOT NULL CHECK (locale IN ('de','en')),
  equipment_configuration VARCHAR NOT NULL,
  prerequisites VARCHAR NOT NULL,
  approach VARCHAR NOT NULL,
  execution VARCHAR NOT NULL,
  exit_reset VARCHAR NOT NULL,
  fallback_exercise VARCHAR NOT NULL,
  station_capacity SMALLINT NOT NULL CHECK (station_capacity > 0),
  clear_zone_metres DECIMAL(5,2) NOT NULL CHECK (clear_zone_metres > 0),
  PRIMARY KEY (exercise_id, locale)
);

CREATE TEMP TABLE obstacle_seed_guidance AS SELECT * FROM (VALUES
('bear-crawl',2.0,'Freie ebene Bahn, rutschfester Boden, kurze markierte Wendestrecke.','Clear level lane, non-slip surface and a short marked turn.','Kann sicher auf Hände und Füße gehen und auf Signal stoppen.','Can move safely on hands and feet and stop on cue.','Starte im Vierfüßlerstand, Hände unter Schultern, Knie knapp über dem Boden.','Begin on all fours with hands under shoulders and knees just off the floor.','Bewege gegenüberliegende Hand und Fuß in kleinen Schritten; halte Rücken ruhig und Blick zum Boden.','Move opposite hand and foot in short steps; keep back steady and eyes on the floor.','Stoppe vor der Markierung, setze die Knie ab und gehe aus der Bahn.','Stop before the marker, lower knees and leave the lane.','Bear-Plank halten oder kurze Vierfüßler-Schritte am Boden.','Hold a bear plank or take short all-fours steps on the floor.'),
('low-crawl',2.0,'Ebene, saubere Matte oder Rasenbahn; Länge kurz halten und Wendemarke setzen.','Use a clean level mat or grass lane; keep it short and mark the turn.','Kann sicher in Bauchlage abstützen und ohne Atemnot aufstehen.','Can support themselves safely prone and rise without breathlessness.','Lege dich hinter die Startlinie, Ellbogen nah am Körper, Blick nach vorn-unten.','Lie behind the start line with elbows close and eyes forward-down.','Ziehe dich mit Unterarmen kontrolliert vor; halte Becken tief und bewege dich nur so weit, dass Atmung frei bleibt.','Pull forward under control with forearms; keep hips low and move only while breathing stays free.','Stoppe an der Markierung, drehe dich auf die Seite und steh über den Vierfüßlerstand auf.','Stop at the marker, roll to your side and rise through all fours.','Vierfüßler-Crawl mit höherem Becken oder kürzere Strecke.','Use a higher all-fours crawl or shorten the distance.'),
('army-crawl',2.0,'Ebene Matte oder weicher, geprüfter Rasen; keine Steine, scharfen Kanten oder Gegenstände im Weg.','Use a level mat or checked soft grass; remove stones, sharp edges and objects.','Kann sicher in Bauchlage liegen, sich abstützen und bei Bedarf sofort stoppen.','Can lie prone, support themselves and stop immediately if needed.','Lege dich flach hinter die Linie und prüfe, dass die gesamte Strecke frei ist.','Lie flat behind the line and check that the full lane is clear.','Ziehe dich abwechselnd mit Unterarm und gegenüberliegendem Bein vor; halte Kopf neutral und Tempo niedrig.','Pull forward using alternating forearm and opposite leg; keep head neutral and pace slow.','Beende an der Markierung, rolle auf die Seite und verlasse die Bahn gehend.','Finish at the marker, roll to your side and walk out of the lane.','Low-Crawl auf den Unterarmen ohne Beinzug oder normaler Vierfüßler-Crawl.','Use a forearm low crawl without leg drive or a regular all-fours crawl.'),
('crab-walk',2.0,'Ebene rutschfeste Fläche; Bahn frei von anderen Gruppen und niedrigen Hindernissen.','Use a level non-slip surface; keep the lane clear of other groups and low obstacles.','Kann sich schmerzfrei rückwärts auf Hände und Füße stützen.','Can support themselves backward on hands and feet without pain.','Setze dich, Hände hinter dem Körper, Füße hüftbreit und Finger seitlich oder nach vorn.','Sit with hands behind, feet hip-width apart and fingers turned sideways or forward.','Hebe das Becken nur so weit, dass du stabil bleibst; gehe kontrolliert Hand und Fuß im Wechsel.','Lift hips only as high as stable; travel by alternating hand and foot under control.','Setze das Becken ab und stehe über eine seitliche Drehung auf.','Lower hips and stand via a side turn.','Becken am Boden lassen und kurze Hand-Fuß-Schritte üben.','Keep hips on the floor and practise short hand-foot steps.'),
('wall-stepover-low',3.0,'Nur freigegebene niedrige, feste Wand mit sicherem Tritt und freier, weicher Landefläche auf beiden Seiten.','Use only an approved low stable wall with a secure step and clear soft landing on both sides.','Kann kontrolliert aufsteigen und absteigen; kennt Stoppzeichen und Wartelinie.','Can step up and down under control; knows stop signal and waiting line.','Warte hinter der Linie, prüfe Wand und Landefläche, gehe frontal ohne Anlauf heran.','Wait behind the line, check wall and landing, approach front-on without a run-up.','Setze einen Fuß auf den vorgesehenen Tritt, drücke dich kontrolliert hoch und steige einzeln über die Wand.','Place one foot on the designated step, rise under control and step over one at a time.','Lande mit beiden Füßen stabil, entferne dich seitlich und gib die Bahn frei.','Land with both feet stable, move aside and clear the lane.','Niedriger Step-up über eine Bodenmarkierung oder niedrige feste Bank.','Use a low step-up over a floor marker or stable low bench.'),
('wall-vault-basic',4.0,'Nur geprüfte niedrige Vereinswand mit geeigneten Griffpunkten, Matten/Landezone und direkter Traineraufsicht.','Use only a checked low club wall with suitable handholds, mats/landing zone and direct coach supervision.','Beherrscht Step-over und kontrollierten Stütz am Boden; kann sicher absteigen.','Has mastered step-over and controlled floor support; can dismount safely.','Warte bis die Wand frei ist; nähere dich gehend und lege die Hände auf die markierten stabilen Griffe.','Wait until the wall is clear; walk in and place hands on marked stable holds.','Übe zuerst den Stütz; verlagere Gewicht über die Hände und führe ein Bein nach dem anderen über die niedrige Wand.','Practise support first; shift weight through hands and bring one leg at a time over the low wall.','Lande auf beiden Füßen, stabilisiere dich und steige aus der Zone.','Land on both feet, stabilise and leave the zone.','Wand-Step-over mit Fußstütze oder niedriger Banküberstieg.','Use a wall step-over with foot support or a low bench step-over.'),
('incline-wall-run',4.0,'Gering geneigte, rutschfeste und freigegebene Trainingsfläche; freie Anlauf-, Auslauf- und Seitenzone.','Use an approved gently inclined non-slip surface with clear approach, run-out and side zones.','Kann auf ebenem Boden abbremsen und sicher gehen; beginnt ohne Sprung- oder Kletterversuch.','Can decelerate on level ground and walk safely; no jumping or climbing attempt at first.','Starte aus kurzem Geh- oder Jogginganlauf; Trainer steht seitlich außerhalb der Laufspur.','Start from a short walk or jog; coach stands to the side outside the lane.','Setze einen Fuß nach dem anderen auf die Schräge, halte den Körper nah an der Fläche und steige nur bis zur markierten niedrigen Höhe.','Place one foot at a time on the incline, stay close to the surface and climb only to the marked low height.','Steige kontrolliert zurück oder über den ausgewiesenen seitlichen Ausgang ab; nicht abspringen.','Descend under control or use the marked side exit; do not jump down.','Step-ups an einer niedrigen schrägen Fläche ohne Anlauf.','Use step-ups on a low incline without a run-up.'),
('cargo-net-climb',4.0,'Niedrig eingestelltes, verankertes und geprüftes Netz; Matten oder geeigneter Fallschutz und abgesperrte Fallzone.','Use a low, anchored and inspected net; add mats or suitable fall protection and close the fall zone.','Kann drei sichere Kontaktpunkte halten und den Abstieg kontrolliert ausführen.','Can maintain three secure points of contact and descend under control.','Warte seitlich hinter der Markierung; prüfe Verankerung, Netzspannung und freie Fallzone.','Wait to the side behind the marker; check anchors, net tension and clear fall zone.','Klettere aufrecht mit Händen und Füßen abwechselnd; halte stets drei Kontaktpunkte und nutze nur die freigegebene Höhe.','Climb upright by alternating hands and feet; keep three points of contact and stay within the approved height.','Steige dieselbe Route rückwärts kontrolliert ab; springe niemals herunter.','Descend the same route under control; never jump down.','Bodennahes Netzqueren oder Kletterbewegung an einer niedrigen Sprossenwand.','Use a ground-level net traverse or climb on a low ladder wall.'),
('cargo-net-traverse',4.0,'Seitlich niedriges, straff verankertes Netz mit Fallschutz; Ein- und Ausstieg markieren, Fallzone sperren.','Use a low side net secured tautly with fall protection; mark entry and exit and close fall zone.','Kann stabil am Netz stehen und jederzeit zur sicheren Seite zurückkehren.','Can stand steadily at the net and return to the safe side at any time.','Warte bis die vorherige Person vollständig ausgestiegen ist; prüfe Netz und Landebereich.','Wait until the previous person has fully exited; check net and landing area.','Bewege dich seitlich mit Händen und Füßen über benachbarte Maschen; löse immer nur einen Kontaktpunkt.','Move sideways using hands and feet on adjacent squares; release only one contact point at a time.','Erreiche den markierten Ausgang und steige dort kontrolliert ab.','Reach the marked exit and descend there under control.','Seitliches Gehen an einer niedrigen, stabilen Stange oder Bodenlinie.','Practise side steps along a low stable rail or floor line.'),
('over-under',3.0,'Niedrige stabile Hindernisse mit großem Abstand; keine scharfen Kanten, Stolperfallen oder Gegenverkehr.','Use low stable obstacles with generous spacing; remove sharp edges, trip hazards and opposing traffic.','Kann sicher kriechen und über eine niedrige Markierung steigen.','Can crawl safely and step over a low marker.','Gehe die Bahn zuerst ab; benenne klar, welches Hindernis über- und welches unterquert wird.','Walk the lane first; clearly identify which obstacle is stepped over and which is crawled under.','Steige über niedrige Hindernisse, gehe danach unter der freien Stange hindurch; halte die Reihenfolge und Blick nach vorn.','Step over low obstacles, then crawl under the clear bar; keep sequence and look ahead.','Gehe nach der letzten Markierung aus der Bahn, wende außerhalb und kehre zurück.','Exit after the last marker, turn outside the lane and return.','Höhe reduzieren und nur steigen oder nur kriechen.','Lower the height and practise only stepping or only crawling.'),
('box-over',3.0,'Niedrige kippsichere Box oder Bank, rutschfester Boden und Matten; seitliche Ausstiegsfläche freihalten.','Use a low non-tipping box or bench, non-slip floor and mats; keep side exit clear.','Kann sicher stützen und kontrolliert auf niedrige Erhöhung auf- und absteigen.','Can support themselves and step on/off a low platform safely.','Stelle dich nah an die Box; prüfe Standfestigkeit und freie Landefläche, bevor du startest.','Stand close to the box; check stability and clear landing before starting.','Stütze die Hände auf, verlagere Gewicht kontrolliert und steige mit einem Bein nach dem anderen hinüber.','Place hands on the box, shift weight under control and step across one leg at a time.','Lande beidfüßig, richte dich auf und gehe seitlich aus dem Stationsbereich.','Land on both feet, stand tall and exit the station to the side.','Niedriger Step-over ohne Stütz oder seitlicher Step-up.','Use a lower step-over without support or a side step-up.'),
('rope-traverse',4.0,'Niedrig gespanntes, fest verankertes Seil über durchgehender Fallschutzfläche; direkte Aufsicht und freie Ausstiegszone.','Use a low taut anchored rope over continuous fall protection; provide direct supervision and clear exit.','Kann stabil hängen oder stützen und kennt Abbruchsignal sowie kontrollierten Abstieg.','Can hang or support steadily and knows the stop signal and controlled dismount.','Prüfe Anker und Seil; warte bis die gesamte Traverse frei ist und greife aus sicherem Stand.','Check anchors and rope; wait until traverse is clear and grip from a secure stance.','Bewege die Hände einzeln entlang des Seils; halte den Körper ruhig und nutze nur den niedrigen freigegebenen Abschnitt.','Move hands one at a time along the rope; keep body controlled and use only the approved low section.','Beende am markierten Ende und steige über die vorgesehene Seite ab, nicht abspringen.','Finish at the marked end and dismount on the designated side; do not jump.','Sitzender Seilzug am Boden oder kurzer unterstützter Hang an niedriger Stange.','Use a seated floor rope pull or a short assisted hang on a low bar.'),
('obstacle-burpee-penalty',2.0,'Ebene rutschfeste Fläche mit Abstand zur Laufspur; Burpee-Variante und Umfang vorher ansagen.','Use a level non-slip surface away from running lanes; explain the burpee version and dose first.','Kann schmerzfrei in die Hocke und wieder zum Stand kommen; Liegestütz ist keine Voraussetzung.','Can squat and stand without pain; a push-up is not required.','Gehe aus der Laufspur in den markierten Bereich und nimm eine stabile Standposition ein.','Move out of the running lane into the marked area and stand steadily.','Setze Hände ab, steige die Füße einzeln zurück, kehre einzeln zurück und richte dich ohne Sprung auf.','Place hands down, step feet back one at a time, step them in and stand without a jump.','Prüfe den freien Weg und gehe erst nach dem Signal zurück auf die Laufbahn.','Check the lane is clear and return only on the signal.','Erhöhte Hände auf Bank oder reine Kniebeuge ohne Bodenphase.','Use hands on a raised bench or a squat without the floor phase.'),
('rig-run-interval',4.0,'Kurze Laufstrecke plus niedriges freigegebenes Rig; getrennte Zu- und Abgänge, Aufsicht an der Station.','Combine a short run with a low approved rig; separate entry/exit routes and supervise station.','Kann kontrolliert laufen, sicher greifen und auf Aufforderung sofort absteigen.','Can run under control, grip safely and dismount immediately on request.','Erkläre Reihenfolge, Laufweg und Warteposition; starte nur bei freier Rig-Station.','Explain sequence, route and waiting position; start only when the rig station is clear.','Laufe locker bis zur Markierung, wechsle gehend zum Rig und führe nur die freigegebene Hang- oder Traversevariante aus.','Run easily to the marker, walk to the rig and perform only the approved hang or traverse variation.','Steige kontrolliert ab, bestätige freie Station und gehe zurück; halte die Runde bei Technikverlust an.','Dismount under control, confirm the station is clear and walk back; stop the round if technique is lost.','Lauf plus bodennahe Griffaufgabe oder lauf plus Seilzug im Sitzen.','Pair running with a ground-level grip task or seated rope pull.'),
('wall-run-transition',4.0,'Niedrige freigegebene Wand mit weicher Landefläche; Laufspur endet vor Wartezone und Wandbereich.','Use an approved low wall with soft landing; end the running lane before the waiting and wall zone.','Kann auf ebener Strecke abbremsen und eine niedrige Wand sicher übersteigen.','Can decelerate on level ground and step over a low wall safely.','Laufe kontrolliert zur Bremsmarkierung, reduziere Tempo und warte bis die Wand frei ist.','Run under control to the braking marker, slow down and wait until the wall is clear.','Gehe an die Wand und übersteige sie mit der geübten niedrigen Variante; kein Anlauf direkt in den Sprung.','Walk to the wall and step over using the practised low variation; do not sprint into a jump.','Lande stabil, verlasse die Landefläche und setze den Lauf erst nach dem Ausgangspunkt fort.','Land steadily, clear the landing area and resume running only beyond the exit marker.','Lauf-Bremsübung plus niedriger Step-over als getrennte Aufgaben.','Practise running deceleration and a low step-over as separate tasks.'),
('crawl-run-transition',3.0,'Ebene weiche Crawlmatte an einer geraden, getrennten Laufspur; Ein- und Ausstieg markieren.','Place a level soft crawl mat beside a straight separate running lane; mark entry and exit.','Kann kontrolliert kriechen, aufstehen und vor der Laufspur warten.','Can crawl under control, stand up and wait before entering the running lane.','Beende den Lauf vor der Matte und warte auf freie Crawlbahn.','Finish the run before the mat and wait until crawl lane is clear.','Krieche die kurze markierte Strecke, stehe außerhalb der Laufspur auf und orientiere dich neu.','Crawl the short marked lane, stand outside the running route and reorient.','Gehe bis zur Startmarkierung und beginne den nächsten Laufabschnitt erst auf Signal.','Walk to the start marker and begin the next running segment only on cue.','Kurze Gehstrecke plus Vierfüßlerbewegung, Lauf und Crawl zunächst getrennt.','Use a short walk and all-fours movement; practise running and crawling separately first.')
) AS v(seed_key,clear_zone_metres,setup_de,setup_en,prereq_de,prereq_en,approach_de,approach_en,execution_de,execution_en,exit_de,exit_en,fallback_de,fallback_en);

INSERT INTO exercise_obstacle_guidance
SELECT e.id,l.locale,
  CASE l.locale WHEN 'de' THEN v.setup_de ELSE v.setup_en END,
  CASE l.locale WHEN 'de' THEN v.prereq_de ELSE v.prereq_en END,
  CASE l.locale WHEN 'de' THEN v.approach_de ELSE v.approach_en END,
  CASE l.locale WHEN 'de' THEN v.execution_de ELSE v.execution_en END,
  CASE l.locale WHEN 'de' THEN v.exit_de ELSE v.exit_en END,
  CASE l.locale WHEN 'de' THEN v.fallback_de ELSE v.fallback_en END,
  1,v.clear_zone_metres
FROM obstacle_seed_guidance v
JOIN exercises e ON e.seed_key=v.seed_key
CROSS JOIN (VALUES ('de'),('en')) l(locale);

UPDATE exercise_details d SET
  setup=g.equipment_configuration,
  prerequisites=g.prerequisites,
  fallback_exercise=g.fallback_exercise,
  start_position=g.approach,
  finish_reset=g.exit_reset,
  quality_criteria=g.execution || ' ' || g.exit_reset,
  safety_notes=CASE WHEN e.risk_level='high'
    THEN CASE d.locale WHEN 'de' THEN 'Direkte Stationsaufsicht ist erforderlich. Gerät vor jedem Durchgang prüfen, Fall- und Landefläche freihalten und nur eine Person auf der Station zulassen. Sofort stoppen bei beschädigtem Gerät, Kontrollverlust oder unsicherem Abstieg.' ELSE 'Direct station supervision is required. Inspect equipment before each turn, keep fall and landing zones clear and allow one person on the station at a time. Stop for damaged equipment, loss of control or unsafe dismount.' END
    ELSE CASE d.locale WHEN 'de' THEN 'Trainer hält die Bahn frei, prüft die Fläche und lässt erst starten, wenn der vorherige Teilnehmende die Station verlassen hat.' ELSE 'Coach keeps the lane clear, checks the surface and allows a start only after the previous participant has left the station.' END END,
  supervision=CASE WHEN e.risk_level='high' THEN 'direct' ELSE 'increased' END,
  station_capacity=g.station_capacity
FROM exercise_obstacle_guidance g
JOIN exercises e ON e.id=g.exercise_id
WHERE d.exercise_id=e.id AND d.locale=g.locale;

DELETE FROM exercise_execution_steps s USING exercise_obstacle_guidance g WHERE s.exercise_id=g.exercise_id AND s.locale=g.locale;
INSERT INTO exercise_execution_steps
SELECT g.exercise_id,g.locale,n.step_order,
  CASE n.step_order WHEN 1 THEN g.approach WHEN 2 THEN g.execution ELSE g.exit_reset END
FROM exercise_obstacle_guidance g CROSS JOIN (VALUES (1),(2),(3)) n(step_order);

UPDATE exercise_common_mistakes m SET
  mistake=CASE m.locale WHEN 'de' THEN 'Der Teilnehmende startet, bevor die Station frei ist, oder überspringt die vorgesehene Annäherung.' ELSE 'The participant starts before the station is clear or skips the planned approach.' END,
  correction=CASE m.locale WHEN 'de' THEN 'Zur Warteposition zurückkehren, erst nach Freigabe starten und die Annäherung Schritt für Schritt ausführen.' ELSE 'Return to the waiting position, start only when cleared and follow the approach one step at a time.' END
FROM exercise_obstacle_guidance g
WHERE m.exercise_id=g.exercise_id AND m.locale=g.locale AND m.mistake_order=1;

INSERT INTO schema_migrations (version,name) VALUES (6,'obstacle_seed_guidance');
DROP TABLE obstacle_seed_guidance;
COMMIT;
