BEGIN TRANSACTION;

CREATE TEMP TABLE grip_rig_seed_guidance AS SELECT * FROM (VALUES
('dead-hang',2.0,'Stabile niedrige Stange mit rutschfester Landefläche; Höhe erlaubt Absprung mit Füßen am Boden.','Use a stable low bar over non-slip flooring; set height so feet can reach the floor.','Kann den eigenen Griff sicher lösen und mit Bodenkontakt entlasten.','Can release grip safely and unload with feet on the floor.','Stelle dich unter die Stange, greife schulterbreit und halte die Füße zunächst am Boden.','Stand under the bar, grip at shoulder width and keep feet on the floor initially.','Verlagere nur so viel Gewicht in die Hände, wie du sicher halten kannst; halte kurz und atme ruhig.','Load only as much weight into the hands as you can hold safely; pause briefly and breathe calmly.','Setze die Füße ab, löse eine Hand nach der anderen und gehe aus der Matte.','Place feet down, release one hand at a time and leave the mat.','Teilhang mit Füßen am Boden oder kurzer Griff an niedriger Stange.','Use a partial hang with feet on the floor or a short grip on a low bar.'),
('active-hang',2.0,'Niedrige fest montierte Stange und freie rutschfeste Abstiegfläche; direkte Sicht der Trainerperson.','Use a securely fixed low bar and clear non-slip dismount area within coach view.','Kann sicher in den Hang ein- und aussteigen und Schulterbewegung kontrollieren.','Can enter and exit a hang safely and control shoulder movement.','Greife die Stange und beginne mit gestreckten Armen und entspannter Schulterposition.','Grip the bar and begin with straight arms and relaxed shoulders.','Ziehe Schulterblätter sanft nach unten, ohne die Ellbogen zu beugen; halte den Rumpf ruhig.','Gently draw shoulder blades down without bending elbows; keep torso steady.','Löse die aktive Spannung, setze Füße kontrolliert auf und steige ab.','Release active tension, place feet down under control and dismount.','Schulterblattbewegung im Stand mit Band oder Teilhang mit Fußstütze.','Practise standing scapular depression with a band or a foot-supported partial hang.'),
('towel-hang',2.0,'Zwei gleich lange, unbeschädigte Handtücher sicher über niedriger Stange fixieren; Matte darunter.','Secure two equal undamaged towels over a low bar; place a mat beneath.','Kann den Griff selbstständig lösen; beginnt mit belasteten Füßen.','Can release grip independently; start with feet bearing some weight.','Prüfe beide Tücher, greife sie gleich hoch und stelle die Füße unter die Stange.','Check both towels, grip at equal height and place feet beneath the bar.','Belaste den Tuchgriff schrittweise und halte den Körper ruhig; Dauer kurz halten.','Load the towel grip gradually and keep body still; keep the hold brief.','Setze Gewicht auf die Füße zurück und löse beide Tücher ohne Fallenlassen.','Transfer weight back to feet and release both towels without dropping.','Sitzender Tuchzug oder stehender Zug mit Füßen am Boden.','Use a seated towel pull or standing pull with feet on the floor.'),
('ring-hang',2.0,'Ringe gleich hoch, Anker geprüft und niedrig eingestellt; Matte und freie Abstiegfläche.','Set rings level, inspect anchors and keep them low; use a mat and clear dismount area.','Kann Stütz oder Teilhang kontrolliert halten und sicher absteigen.','Can hold a support or partial hang and dismount safely.','Greife beide Ringe, prüfe gleiche Höhe und beginne mit Füßen am Boden.','Grip both rings, check equal height and begin with feet on the floor.','Verlagere kontrolliert Gewicht in die Hände; halte Ringe nah am Körper und vermeide Pendeln.','Shift weight into hands under control; keep rings close and avoid swinging.','Setze die Füße auf und löse die Ringe nacheinander.','Place feet down and release rings one at a time.','Teilhang mit Fußkontakt oder Ringstütz mit elastischer Unterstützung.','Use a foot-supported partial hang or ring support with elastic assistance.'),
('ring-row',2.0,'Ringe sicher verankern und auf Brusthöhe einstellen; Boden frei und nicht rutschig.','Anchor rings securely at chest height; keep floor clear and non-slip.','Kann eine stabile Körperlinie in leichter Schräglage halten.','Can hold a stable body line at a shallow angle.','Greife die Ringe, gehe mit den Füßen vor und lehne dich nur leicht zurück.','Grip rings, walk feet forward and lean back only slightly.','Ziehe Brust zwischen die Ringe, halte Körper gerade und führe die Arme kontrolliert zurück.','Pull chest between rings, keep body straight and lower arms under control.','Stelle dich aufrecht, gehe zurück und löse die Ringe im Stand.','Stand upright, step back and release rings while standing.','Aufrechter Bandzug oder weniger Schräglage mit Füßen näher an den Ringen.','Use an upright band row or reduce the lean by moving feet closer to rings.'),
('ring-traverse',3.0,'Ringe niedrig, dicht genug für erreichbare Übergänge, Anker und Fallschutz geprüft; nur eine Person auf dem Abschnitt.','Set rings low and close enough for reachable transfers; inspect anchors and fall protection; one person per section.','Kann kontrolliert hängen, einzeln umgreifen und jederzeit sicher absteigen.','Can hang under control, move one hand at a time and dismount safely at any point.','Warte bis der Abschnitt frei ist; greife den ersten Ring aus stabilem Stand.','Wait until the section is clear; take the first ring from a stable stance.','Bewege eine Hand zum nächsten Ring, stabilisiere den Griff und folge erst dann mit der anderen.','Move one hand to the next ring, stabilise the grip and only then follow with the other.','Erreiche den Endmarker, setze Füße auf und gehe seitlich aus dem Fallbereich.','Reach the end marker, place feet down and leave the fall zone to the side.','Bodennahes Umgreifen an festen Griffen oder unterstütztes Ringhangeln.','Practise low hand transfers on fixed holds or assisted ring traversal.'),
('monkeybars-basic',3.0,'Niedrige geprüfte Sprossenleiter mit Matten; Einstieg und Ausstieg eindeutig markieren.','Use a low inspected monkey-bar ladder with mats; mark entry and exit clearly.','Kann sicher greifen und Sprosse für Sprosse mit sicherem Abstieg bewältigen.','Can grip safely and move rung by rung with a safe dismount.','Warte bis die Leiter frei ist; greife die erste Sprosse aus dem Stand.','Wait until the ladder is clear; reach the first rung from standing.','Greife jede nächste Sprosse einzeln; bewege dich langsam und halte den Körper ruhig.','Take each next rung one at a time; move slowly and keep body controlled.','Löse am Endmarker den Griff erst mit Bodenkontakt oder Trainerhilfe.','At the end marker release only with feet grounded or coach assistance.','Seitliches Hangeln an niedriger fester Stange mit Fußkontakt.','Use side transfers on a low fixed bar with feet supported.'),
('monkeybars-skip',3.0,'Niedrige Sprossen mit engem Abstand, Matten und direkter Aufsicht; keine ermüdete oder nasse Nutzung.','Use low bars with close rung spacing, mats and direct supervision; no fatigued or wet attempts.','Beherrscht mehrere normale Sprossenübergänge und kontrollierten Abstieg.','Has mastered several normal rung transfers and a controlled dismount.','Beginne an der ersten Sprosse mit beiden Händen stabil; Trainer bestätigt freien Bereich.','Start at the first rung with both hands secure; coach confirms the area is clear.','Überspringe höchstens eine Sprosse, greife zuerst sicher und verlagere Gewicht erst nach geschlossenem Griff.','Skip at most one rung, secure the grip first and transfer weight only after the hold is closed.','Beende vor Griffverlust am vorgesehenen Punkt und steige kontrolliert ab.','Finish before grip failure at the designated point and dismount under control.','Monkey Bars Basis ohne übersprungene Sprossen.','Use basic monkey bars without skipping rungs.'),
('lateral-bar-traverse',3.0,'Niedrige feste Querstrecke mit Matten und markierten Seiten; Station nacheinander nutzen.','Use a low fixed traverse with mats and marked sides; take turns one at a time.','Beherrscht den sicheren Teilhang und seitliches Umgreifen mit Fußhilfe.','Has mastered a safe partial hang and lateral hand transfer with foot support.','Greife die Stange seitlich und stelle Füße so, dass du jederzeit entlasten kannst.','Grip the bar side-on and position feet so you can unload at any time.','Löse immer nur eine Hand, setze sie seitlich um und stabilisiere vor dem nächsten Wechsel.','Release one hand at a time, move it sideways and stabilise before the next transfer.','Erreiche den Endmarker, setze Füße auf und steige zur markierten Seite ab.','Reach the end marker, place feet down and dismount on the marked side.','Seitliches Umgreifen im Teilhang mit dauerhaftem Fußkontakt.','Practise lateral transfers in a partial hang with continuous foot contact.'),
('rope-grip-hold',2.0,'Dickes unbeschädigtes Seil an niedrigem geprüften Anker; Matte, freier Stand und kein Kletterversuch.','Use a thick undamaged rope on a low inspected anchor; mat and clear stance; no climbing attempt.','Kann Griffkraft dosieren und vor Ermüdung selbstständig absetzen.','Can dose grip effort and release before fatigue.','Stelle dich nah an das Seil, greife auf Brusthöhe und lasse die Füße fest am Boden.','Stand close to the rope, grip at chest height and keep feet planted.','Ziehe das Seil leicht zu dir und halte nur so stark, dass Handgelenke und Schultern ruhig bleiben.','Pull rope lightly toward you and hold only as firmly as needed to keep wrists and shoulders steady.','Löse die Spannung, öffne die Hände und gehe vom Seil zurück.','Release tension, open hands and step away from the rope.','Kurze Haltezeit am Seil im Sitzen oder Handtuchgriff im Stand.','Use a short seated rope hold or standing towel grip.'),
('rope-pull-seated',2.0,'Seil und Anker prüfen; sitzende Position auf rutschfester Matte, freie Seilbahn ohne Schlaufen am Hals/Fuß.','Inspect rope and anchor; sit on non-slip mat with a clear rope path and no loops near neck or feet.','Kann aufrecht sitzen und Last kontrolliert nachlassen.','Can sit upright and release load under control.','Setze dich mit leicht gebeugten Knien hin, greife das Seil und spanne es ohne Ruck.','Sit with knees slightly bent, grip rope and take up slack without jerking.','Ziehe Hand über Hand zum Körper, halte Brust aufrecht und gib das Seil kontrolliert zurück.','Pull hand over hand toward the body, stay upright and feed rope back under control.','Lege das Seil spannungsfrei ab und stehe erst danach auf.','Lay rope down slack before standing.','Leichter Bandzug im Sitzen oder Zug mit kürzerer Seilstrecke.','Use a light seated band row or a shorter rope pull.'),
('rope-climb-footlock',4.0,'Niedrig eingestelltes Kletterseil, geprüfter Anker, Fallschutz und direkte qualifizierte Stationsaufsicht.','Use a low climbing rope with inspected anchor, fall protection and direct qualified station supervision.','Beherrscht sitzenden Seilzug und Fußklemmtechnik bodennah; kennt Stoppsignal.','Has mastered seated rope pull and low foot lock practice; knows stop signal.','Prüfe Seil und Freiraum; beginne sitzend oder stehend mit beiden Händen am Seil, ohne Anlauf.','Check rope and clear area; begin seated or standing with both hands on rope and no run-up.','Klemme das Seil mit den Füßen, stehe nur niedrig auf und führe Hände nach; Trainer kontrolliert jeden Schritt.','Clamp rope with feet, rise only a short distance and move hands up; coach checks every step.','Steige dieselbe kurze Strecke kontrolliert ab; springe nicht und lasse das Seil nicht los.','Descend the same short distance under control; do not jump or release rope.','Bodennahes Fußklemm-Üben im Sitzen plus sitzender Seilzug.','Practise foot lock at floor level while seated plus seated rope pull.'),
('scapular-swing',2.0,'Niedrige Stange, rutschfeste Landefläche und genügend Freiraum für kleine Bewegungen.','Use a low bar, non-slip landing and enough clearance for small movements.','Kann aktiven Hang halten und Spannung vor Kontrollverlust lösen.','Can hold an active hang and release before losing control.','Greife stabil, beginne im aktiven Hang und halte die Bewegung zunächst sehr klein.','Take a secure grip, begin in an active hang and keep movement very small initially.','Bewege den Brustkorb wenige Zentimeter vor und zurück aus den Schultern; kein kräftiges Kipping.','Move chest a few centimetres forward and back through shoulders; avoid forceful kipping.','Stoppe die Bewegung, setze Füße auf und löse den Griff kontrolliert.','Stop movement, place feet down and release grip under control.','Aktive Schulterblattbewegung mit Füßen gestützt im Stand.','Practise active scapular movement standing with feet supported.'),
('rig-transition',3.0,'Niedriges geprüftes Rig, Matte und markierte Warteposition; Trainer beaufsichtigt Griffwechsel einzeln.','Use a low inspected rig, mat and marked waiting spot; coach supervises individual grip changes.','Beherrscht stabilen Hang und kann Füße zum Entlasten sicher aufsetzen.','Has mastered a stable hang and can place feet down to unload safely.','Beginne an einem niedrigen Griff mit Füßen nah am Boden und prüfe den nächsten Griff.','Start from a low hold with feet near the floor and check the next hold.','Belaste den Zielgriff zuerst mit einer Hand; wechsle erst nach sicherem Halt die zweite Hand.','Load the target hold with one hand first; move the second hand only after the first is secure.','Setze Füße ab, prüfe den Griff und verlasse die Matte nach Freigabe.','Place feet down, check the hold and leave the mat when cleared.','Griffwechsel an zwei bodennahen Griffen mit dauerhaftem Fußkontakt.','Practise transfers between two low holds with continuous foot contact.'),
('assisted-rig-traverse',3.0,'Niedrige Traverse, stabile Fußstütze oder Trainerhilfe und Matte; Anker vor Nutzung prüfen.','Use a low traverse with stable foot support or coach assistance and mat; inspect anchors first.','Kann sicher greifen und auf Zuruf sofort pausieren oder absteigen.','Can grip safely and pause or dismount immediately on cue.','Greife den ersten Halt mit Füßen auf der Unterstützung; Trainer erklärt Route und Hilfestellung.','Take the first hold with feet on support; coach explains route and spotting.','Bewege dich seitlich, halte Füße unterstützt und löse immer nur einen Griffpunkt zugleich.','Move sideways with feet supported and release only one grip point at a time.','Stoppe am Endmarker, steige über die Unterstützung ab und gehe aus dem Bereich.','Stop at the end marker, dismount using support and leave the area.','Bodennahes seitliches Umgreifen an festen Griffen.','Practise low lateral hand transfers on fixed holds.')
) AS v(seed_key,clear_zone_metres,setup_de,setup_en,prereq_de,prereq_en,approach_de,approach_en,execution_de,execution_en,exit_de,exit_en,fallback_de,fallback_en);

INSERT INTO exercise_obstacle_guidance
SELECT e.id,l.locale,
  CASE l.locale WHEN 'de' THEN v.setup_de ELSE v.setup_en END,
  CASE l.locale WHEN 'de' THEN v.prereq_de ELSE v.prereq_en END,
  CASE l.locale WHEN 'de' THEN v.approach_de ELSE v.approach_en END,
  CASE l.locale WHEN 'de' THEN v.execution_de ELSE v.execution_en END,
  CASE l.locale WHEN 'de' THEN v.exit_de ELSE v.exit_en END,
  CASE l.locale WHEN 'de' THEN v.fallback_de ELSE v.fallback_en END,
  1,v.clear_zone_metres
FROM grip_rig_seed_guidance v
JOIN exercises e ON e.seed_key=v.seed_key
CROSS JOIN (VALUES ('de'),('en')) l(locale);

UPDATE exercise_details d SET
  setup=g.equipment_configuration,
  prerequisites=g.prerequisites,
  fallback_exercise=g.fallback_exercise,
  start_position=g.approach,
  finish_reset=g.exit_reset,
  quality_criteria=g.execution || ' ' || g.exit_reset,
  safety_notes=CASE WHEN e.risk_level='high'
    THEN CASE d.locale WHEN 'de' THEN 'Direkte Stationsaufsicht ist erforderlich. Anker, Griffpunkte und Fallschutz vor jedem Durchgang prüfen; nur eine Person auf der Station. Absteigen statt abspringen und bei Griffverlust, Schmerzen oder beschädigtem Gerät sofort stoppen.' ELSE 'Direct station supervision is required. Check anchors, holds and fall protection before each turn; allow one person on the station. Dismount instead of jumping and stop for grip failure, pain or damaged equipment.' END
    ELSE CASE d.locale WHEN 'de' THEN 'Trainer prüft Gerät und Landefläche, lässt nacheinander starten und erinnert daran, vor Ermüdung kontrolliert abzusteigen.' ELSE 'Coach checks equipment and landing area, sends athletes one at a time and reminds them to dismount under control before fatigue.' END END,
  supervision=CASE WHEN e.risk_level='high' THEN 'direct' ELSE 'increased' END,
  station_capacity=g.station_capacity
FROM exercise_obstacle_guidance g
JOIN exercises e ON e.id=g.exercise_id
WHERE d.exercise_id=e.id AND d.locale=g.locale;

DELETE FROM exercise_execution_steps s USING exercise_obstacle_guidance g WHERE s.exercise_id=g.exercise_id AND s.locale=g.locale;
INSERT INTO exercise_execution_steps
SELECT g.exercise_id,g.locale,n.step_order,
  CASE n.step_order WHEN 1 THEN g.approach WHEN 2 THEN g.execution ELSE g.exit_reset END
FROM exercise_obstacle_guidance g CROSS JOIN (VALUES (1),(2),(3)) n(step_order);

UPDATE exercise_common_mistakes m SET
  mistake=CASE m.locale WHEN 'de' THEN 'Der Teilnehmende greift weiter oder wechselt den Griff, obwohl die aktuelle Position nicht stabil ist.' ELSE 'The participant reaches or changes grip before the current position is stable.' END,
  correction=CASE m.locale WHEN 'de' THEN 'Bewegung anhalten, Füße zum Entlasten aufsetzen und erst nach sicherem Griff kontrolliert fortsetzen.' ELSE 'Pause, place feet down to unload and continue only after a secure grip is established.' END
FROM exercise_obstacle_guidance g
WHERE m.exercise_id=g.exercise_id AND m.locale=g.locale AND m.mistake_order=1;

INSERT INTO schema_migrations (version,name) VALUES (7,'grip_rig_seed_guidance');
DROP TABLE grip_rig_seed_guidance;
COMMIT;
