BEGIN TRANSACTION;

CREATE TEMP TABLE warmup_seed_enrichment AS
SELECT * FROM (VALUES
('easy-jog','de','Lockeres Einlaufen baut die Belastung schrittweise auf und macht den Laufstil vor dem Hauptteil beobachtbar.','Erhöht die Körpertemperatur ohne die Gruppe vorzeitig zu ermüden; der Trainer kann Atmung und Laufbild prüfen.','Markiere eine ebene, rutschfeste Schleife mit breiten Wendungen und freier Auslaufzone.','Gehe zunächst aufrecht los; Blick voraus, Schultern locker und Arme pendeln neben dem Körper.','Bei Stolperstelle, Atemnot, Schmerz oder zunehmender Unsicherheit sofort ins Gehen wechseln und Strecke freigeben.','Gleichmäßige leise Schritte, lockere Hände und vollständige Sätze beim Sprechen bleiben möglich.','4 Minuten zügig gehen, dann 4 Minuten sehr locker joggen.','6–8 Minuten am Stück im Gesprächstempo.','10 Minuten locker; nur die letzten 2 Minuten leicht steigern, solange die Gruppe entspannt bleibt.','Das Tempo ist absichtlich leicht; wer nicht sprechen kann, geht bis die Atmung ruhig ist.','Mit 2 Minuten Gehen und 2 Minuten lockerem Traben beginnen.','Ohne Gehpausen 8 Minuten gleichmäßig joggen.','Auf den letzten 2 Minuten die Schrittfrequenz leicht erhöhen, nicht sprinten.','Kinder laufen eine kurze markierte Runde und wählen selbst zwischen Gehen und Traben; niemand wird abgehängt.','Die Runde sicher gehend absolvieren und dabei den Weg frei halten.','Durch zügiges Gehen auf derselben Strecke ersetzen.'
),('easy-jog','en','Easy jogging raises effort gradually and lets the coach observe running form before the main work.','Raises body temperature without tiring the group; the coach can check breathing and running mechanics.','Mark a flat, non-slip loop with wide turns and a clear run-out area.','Start with an upright walk; look ahead, relax the shoulders and swing the arms beside the body.','Walk and clear the route for a trip hazard, pain, unusual breathlessness or loss of control.','Quiet even steps, relaxed hands and the ability to speak in full sentences.','Walk briskly for 4 minutes, then jog easily for 4 minutes.','Jog continuously for 6–8 minutes at conversational effort.','Jog easily for 10 minutes; slightly increase pace only for the final 2 minutes if relaxed.','Keep effort easy; anyone unable to speak comfortably walks until breathing settles.','Begin with 2 minutes walking and 2 minutes easy jogging.','Jog steadily for 8 minutes without walk breaks.','Slightly raise cadence for the final 2 minutes; do not sprint.','Children use a short marked loop and choose between walking and jogging; keep the group together without chasing.','Walk the marked route and keep the path clear.','Replace with brisk walking on the same route.'
),('walk-jog','de','Der Wechsel aus Gehen und lockerem Laufen übt einen selbst gesteuerten Einstieg in Ausdauerbelastung.','Vermittelt, Belastung und Erholung bewusst zu wechseln und ein Tempo zu finden, das über mehrere Abschnitte tragbar ist.','Lege eine ebene Wendestrecke fest und erkläre gut hörbar das Wechselzeichen; halte Gegenverkehr aus der Bahn.','Starte gehend mit aufrechtem Oberkörper und beginne den Trab erst auf das vereinbarte Signal.','Bei rutschigem Boden, stechendem Schmerz oder Schwindel aussteigen und den Trainer informieren.','Der Wechsel erfolgt ohne abrupten Sprint; im Laufabschnitt bleibt ruhige Nasen- oder Lippenatmung möglich.','6-mal 1 Minute gehen und 1 Minute traben.','8-mal 90 Sekunden traben und 60 Sekunden gehen.','6-mal 3 Minuten locker laufen und 1 Minute gehen.','Gehpausen sind geplant und kein Wettkampf; niemand muss andere einholen.','6 Wechsel mit je 30 Sekunden Gehen und Traben.','8 Wechsel mit 90 Sekunden Traben und 60 Sekunden Gehen.','10 Wechsel mit 2 Minuten Laufen und 30 Sekunden Gehen.','Signalkarten zeigen Gehen oder Traben; kurze Abschnitte und freie Wahl sorgen für Erfolgserlebnisse.','Auf der markierten Route sicher gehen und auf die Wechselzeichen reagieren können.','Statt Traben durch zügiges Gehen mit denselben Wechselzeiten ersetzen.'
),('walk-jog','en','Alternating walking and easy jogging practises self-paced entry into endurance work.','Teaches athletes to switch deliberately between effort and recovery and choose a pace they can sustain.','Set a flat out-and-back route and explain the audible change signal; keep opposing traffic out of the lane.','Begin walking upright and start jogging only at the agreed signal.','Stop and tell the coach if the surface is slippery or sharp pain or dizziness occurs.','Transitions are smooth rather than sprinting; breathing stays calm during each jogging interval.','Complete 6 rounds of 1 minute walking and 1 minute jogging.','Complete 8 rounds of 90 seconds jogging and 60 seconds walking.','Complete 6 rounds of 3 minutes easy running and 1 minute walking.','Walk breaks are planned recovery, not a race; no one needs to catch another athlete.','Complete 6 changes of 30 seconds walking and jogging.','Complete 8 rounds of 90 seconds jogging and 60 seconds walking.','Complete 10 rounds of 2 minutes running and 30 seconds walking.','Use walk or jog signal cards; keep intervals short and let children choose their pace.','Walk the marked route safely and respond to the change signal.','Replace jogging with brisk walking for the same intervals.'
),('high-knees','de','Der Kniehebelauf bereitet Hüftbeugung und Fußaufsatz für Lauf-ABC und kurze Beschleunigungen vor.','Trainiert aktiven Abdruck und Rhythmus; die Kniehöhe bleibt der Beweglichkeit und Kontrolle angepasst.','Markiere eine 10–15-Meter-Bahn mit sicherer Auslaufzone; beginne ohne Hütchen oder Hindernisse.','Stehe groß, spanne den Rumpf leicht an und halte die Arme in lockerer Laufposition.','Bei hartem Aufstampfen, Gleichgewichtsverlust oder Beschwerden Tempo reduzieren und auf normales Gehen wechseln.','Der Fuß setzt unter dem Körper auf; der Oberkörper bleibt ruhig und die Bewegung federt leise.','2 Durchgänge à 10 Meter im Marsch mit deutlicher Kniehebung.','3 Durchgänge à 15 Meter locker und rhythmisch; zurückgehen.','4 Durchgänge à 20 Meter mit etwas höherer Schrittfrequenz bei unveränderter Kontrolle.','Knie nur so hoch heben, wie Becken und Oberkörper ruhig bleiben; Geschwindigkeit ist kein Ziel.','Auf der Stelle abwechselnd das Knie bis zur angenehmen Höhe heben.','15 Meter mit aktivem Armschwung und ruhigem Oberkörper laufen.','20 Meter rhythmisch laufen und danach kontrolliert auslaufen.','Als Marschspiel über kurze Distanzen; die Kinder wählen Kniehöhe und Tempo selbst.','Auf der Stelle mit sicherem Stand abwechselnd die Knie heben.','Durch zügiges Marschieren auf ebener Fläche ersetzen.'
),('high-knees','en','High knees prepare hip drive and foot placement for running drills and short accelerations.','Practises an active push-off and rhythm; knee height stays within the athlete’s mobility and control.','Mark a 10–15 metre lane with a safe run-out; begin without cones or obstacles.','Stand tall, lightly brace the trunk and hold the arms in a relaxed running position.','Reduce pace or return to walking if steps become loud, balance is lost or discomfort appears.','Feet land beneath the body; the torso stays quiet and steps remain light.','Complete 2 x 10 metres marching with clear knee lift.','Complete 3 x 15 metres with an easy rhythm; walk back.','Complete 4 x 20 metres with a slightly quicker cadence while keeping control.','Lift only as high as the pelvis and torso stay steady; speed is not the goal.','March in place and lift each knee to a comfortable height.','Run 15 metres with active arm swing and a quiet torso.','Run rhythmically for 20 metres, then decelerate under control.','Use a short marching game; children choose a comfortable knee height and pace.','Alternate knee lifts while standing in a stable spot.','Replace with brisk marching on a flat surface.'
),('butt-kicks','de','Anfersen vermittelt einen schnellen, lockeren Beinrückholweg als Lauf-ABC-Variante.','Übt den Rhythmus der Beinrückführung, ohne dass die Ferse den Po erreichen muss.','Nutze eine ebene 10–15-Meter-Bahn mit freiem Rückweg; demonstriere zuerst langsames Lauf-ABC.','Stehe aufrecht, beuge die Arme und laufe mit kleinen, lockeren Schritten an.','Keine Ferse zum Gesäß ziehen oder Knie nach hinten drücken; bei Zuggefühl abbrechen.','Die Ferse schwingt locker nach hinten, der Fuß landet unter der Hüfte und der Kopf bleibt ruhig.','2 x 10 Meter im lockeren Marsch mit kleiner Fersenbewegung.','3 x 15 Meter als leichtes Lauf-ABC; auf dem Rückweg gehen.','4 x 20 Meter etwas flüssiger, aber nur bei unverändert leisem Fußaufsatz.','Die Ferse muss das Gesäß nicht berühren; eine kleine schmerzfreie Bewegung genügt.','Auf der Stelle abwechselnd die Ferse locker nach hinten führen.','15 Meter mit leichtem Lauf und natürlicher Fersenrückführung.','20 Meter mit flüssigem Rhythmus und anschließendem kontrolliertem Auslaufen.','Als langsames Laufspiel in kurzen Bahnen; auf kleine, leichte Schritte achten.','Im Stand abwechselnd die Fersen leicht anheben und sicher absetzen.','Durch lockeres Traben ohne betonte Fersenbewegung ersetzen.'
),('butt-kicks','en','Butt kicks practise a quick, relaxed leg recovery as a running drill.','Builds the rhythm of the recovery phase; the heel does not need to touch the glute.','Use a flat 10–15 metre lane with a clear return path; demonstrate the drill slowly first.','Stand tall, bend the arms and start with small, relaxed running steps.','Do not pull the heel to the glute or force the knee back; stop if the front of the knee feels strained.','The heel swings back loosely, the foot lands under the hip and the head remains steady.','Complete 2 x 10 metres marching with a small heel lift.','Complete 3 x 15 metres as a light running drill; walk back.','Complete 4 x 20 metres at a smoother rhythm only if steps stay quiet.','The heel need not touch the glute; a small pain-free movement is enough.','Stand in place and alternate a relaxed heel lift behind you.','Run 15 metres with a light stride and natural heel recovery.','Run 20 metres with a smooth rhythm, then decelerate under control.','Use a slow short-lane running game and cue small, light steps.','Alternate small heel lifts while standing securely.','Replace with easy jogging without an exaggerated heel lift.'
),('side-shuffle','de','Der Seitgalopp trainiert seitliche Fortbewegung und kontrolliertes Abbremsen ohne Überkreuzen der Füße.','Bereitet Hüfte und Sprunggelenk auf seitliche Richtungswechsel im Spielfeld vor.','Markiere zwei Linien im Abstand von 5–8 Metern; halte die Bahn frei und vermeide rutschigen Boden.','Stelle dich seitlich zur Laufrichtung, Füße hüftbreit, Knie weich und Blick voraus.','Überkreuze die Füße nicht; Abstand so wählen, dass niemand in die Nachbarbahn gerät.','Die Füße bleiben parallel, Schritte sind klein und die Hüfte sinkt nur leicht ab.','4 x 5 Meter je Richtung im Gehtempo.','4 x 8 Meter je Richtung mit ruhigem Seitgalopp; an der Linie stabil stoppen.','5 x 10 Meter je Richtung, nur bei sicherem Stopp etwas flüssiger.','Kleine Schritte und Platz in der eigenen Bahn haben Vorrang vor Tempo.','Seitlich 3–5 Meter gehen und an jeder Linie sicher anhalten.','8 Meter seitgaloppieren und vor der Linie kontrolliert stoppen.','10 Meter je Richtung mit klarer Beschleunigung und sauberem Stopp.','Linien-Spiel in Paaren: seitlich zur Linie und auf ein Signal stehen bleiben; ohne Ausscheidung.','Zwischen nahen Linien seitlich gehen und auf das Stoppsignal reagieren.','Durch seitliches Gehen auf kürzerer Strecke ersetzen.'
),('side-shuffle','en','The side shuffle trains lateral travel and controlled braking without crossing the feet.','Prepares hips and ankles for lateral changes of direction in field sports.','Mark two lines 5–8 metres apart; keep the lane clear and avoid slippery ground.','Face sideways to the lane with feet hip-width apart, soft knees and eyes forward.','Do not cross the feet; use separate lanes so athletes cannot collide.','Feet stay parallel, steps stay short and the hips lower only slightly.','Complete 4 x 5 metres in each direction at walking pace.','Complete 4 x 8 metres each way and stop steadily at the line.','Complete 5 x 10 metres each way; increase flow only if every stop is controlled.','Short steps and space in the lane matter more than speed.','Side-step 3–5 metres between close lines and stop safely.','Shuffle 8 metres and brake under control before the line.','Cover 10 metres each way with a clear acceleration and controlled stop.','Use a paired line game: shuffle to the line and freeze on a signal; no elimination.','Side-walk between nearby lines and respond to the stop signal.','Replace with slower lateral walking over a shorter distance.'
),('carioca','de','Carioca verbindet seitliche Fortbewegung mit einer kontrollierten Überkreuzkoordination.','Schult Hüftrotation und Schrittkoordination in moderatem Tempo als Vorbereitung auf Richtungswechsel.','Richte eine ebene 8–10-Meter-Bahn mit viel Abstand zwischen den Personen ein; zeige die Schrittfolge im Stand.','Stehe seitlich zur Bahn, Knie leicht gebeugt und Arme locker zur Balance geöffnet.','Nur so weit überkreuzen, dass das Standbein stabil bleibt; bei Stolpern sofort anhalten.','Der Oberkörper bleibt weitgehend nach vorn gerichtet und die Schritte bleiben leicht und rhythmisch.','2 x 8 Meter langsam mit Gehschrittfolge, beide Richtungen.','3 x 10 Meter locker; beim Richtungswechsel neu sortieren statt herumzudrehen.','4 x 10 Meter mit flüssigem Rhythmus, nicht mit maximaler Geschwindigkeit.','Die Kreuzschritte klein halten; zuerst Schrittfolge, danach erst Rhythmus.','Schrittfolge im Stand üben: vor dem Standbein kreuzen und seitlich öffnen.','8 Meter pro Richtung mit sicherer Schrittfolge gehen.','10 Meter pro Richtung flüssig laufen und am Ende kontrolliert stoppen.','Schrittfolge als langsames Spiegelspiel; Kinder bleiben in markierten Einzelbahnen.','Im Stand einen Fuß vor dem anderen kreuzen und wieder öffnen.','Durch Seitgalopp ohne Überkreuzen ersetzen.'
),('carioca','en','Carioca combines lateral travel with controlled crossing-step coordination.','Develops hip rotation and footwork at moderate pace as preparation for direction changes.','Set a flat 8–10 metre lane with generous spacing; teach the foot pattern while stationary.','Face sideways to the lane with soft knees and arms relaxed for balance.','Cross only as far as the stance leg remains stable; stop immediately after a stumble.','Keep the torso mostly facing forward and steps light and rhythmic.','Complete 2 x 8 metres slowly using the walking pattern in both directions.','Complete 3 x 10 metres easily; reset the pattern before changing direction.','Complete 4 x 10 metres with a fluent rhythm, never at maximum speed.','Keep crossing steps small; learn the pattern before increasing rhythm.','Practise in place: cross in front of the stance leg, then step sideways open.','Walk 8 metres in each direction with a secure pattern.','Travel 10 metres each way smoothly and stop under control.','Use a slow mirror-footwork game in marked individual lanes.','Cross one foot in front while standing, then return to the open stance.','Replace with a side shuffle without crossing the feet.'
),('arm-circles','de','Armkreisen bewegt das Schultergelenk kontrolliert durch einen schmerzfreien Bewegungsbogen.','Bereitet Schultern und oberen Rücken auf Stütz-, Wurf- oder Zugbewegungen vor; die Größe wächst nur mit guter Kontrolle.','Stelle die Gruppe mit Armlänge Abstand auf; kein Material nötig.','Stehe stabil, Knie locker, Rippen über dem Becken und Arme seitlich auf Schulterhöhe.','Bei stechendem Schmerz oder Taubheitsgefühl sofort stoppen und den Kreis kleiner machen.','Rumpf und Rippen bleiben ruhig; beide Arme bewegen sich gleichmäßig ohne Schwung.','Je 8 kleine Kreise vorwärts und rückwärts.','Je 10 mittlere Kreise vorwärts und rückwärts, entspannt atmen.','Je 12 kontrollierte Kreise; den Bewegungsbogen nur bei Wohlgefühl vergrößern.','Kreisgröße schmerzfrei wählen und Schulterhochziehen vermeiden.','Arme unter Schulterhöhe halten und je 6 kleine Kreise ausführen.','Je 10 Kreise auf Schulterhöhe in beide Richtungen.','Je 12 größere kontrollierte Kreise ohne Rumpfbewegung.','Als gemeinsames Spiegeln kleiner und großer Kreise; jedes Kind bleibt im eigenen Abstand.','Arme locker hängen lassen und kleine Kreise nur im angenehmen Bereich machen.','Durch Schulterblatt-Zusammenziehen und -Lösen mit Armen am Körper ersetzen.'
),('arm-circles','en','Arm circles move the shoulder joint through a controlled, pain-free range.','Prepare the shoulders and upper back for support, throwing or pulling; enlarge the circle only while control remains.','Space athletes an arm’s length apart; no equipment is needed.','Stand steadily with soft knees, ribs stacked over pelvis and arms at shoulder height.','Stop for sharp pain or numbness and reduce the circle size if movement feels uncomfortable.','Keep the trunk and ribs still; both arms move evenly without momentum.','Complete 8 small circles forward and backward.','Complete 10 medium circles in each direction while breathing easily.','Complete 12 controlled circles; enlarge the range only if comfortable.','Choose a pain-free circle and avoid shrugging the shoulders.','Keep arms below shoulder height and make 6 small circles each way.','Complete 10 circles at shoulder height in both directions.','Complete 12 larger controlled circles without moving the trunk.','Mirror small and large circles together while each child keeps personal space.','Let arms hang and make small circles only in a comfortable range.','Replace with shoulder-blade squeezes and releases with arms by the sides.'
),('inchworm','de','Der Inchworm verbindet eine kurze Rumpfstützphase mit kontrolliertem Vorbeugen und Schulterbewegung.','Erwärmt Schultern, Rumpf und hintere Beinlinie; die Hände wandern nur so weit, wie der Rücken stabil bleibt.','Nutze rutschfeste Matten oder einen sauberen Boden und lasse mindestens zwei Armlängen Abstand.','Stehe hüftbreit und beuge die Knie so weit, dass die Hände den Boden sicher erreichen.','Bei Handgelenksschmerz auf Fäuste oder erhöhte Hände wechseln; nicht in eine schmerzhafte Dehnung drücken.','Beim Wandern bleiben die Schritte klein; in der Stützposition bilden Kopf, Rumpf und Becken eine Linie.','4 Wiederholungen mit gebeugten Knien und kurzer Stützzeit.','6 langsame Wiederholungen; Hände vorlaufen und Füße in kleinen Schritten nachführen.','8 Wiederholungen mit stabiler Stützposition und etwas längerer Reichweite.','Die Knie dürfen gebeugt bleiben; Reichweite endet bevor der untere Rücken durchhängt.','Hände auf eine Bank setzen und 4 kurze Vor- und Rückwege machen.','6 Wiederholungen am Boden mit gebeugten Knien.','8 Wiederholungen mit gestreckteren Beinen, sofern der Rücken stabil bleibt.','Als Raupen-Weg über kurze Distanz; langsames Tempo und freie Matte für jedes Kind.','Hände auf eine erhöhte Fläche setzen und nur wenige Schritte vorlaufen.','Durch erhöhten Wandstütz mit abwechselndem Schultertippen ersetzen.'
),('inchworm','en','The inchworm links a short bracing position with a controlled forward fold and shoulder movement.','Warms shoulders, trunk and hamstrings; walk the hands only as far as the back stays steady.','Use non-slip mats or a clean floor and leave at least two arm-lengths between athletes.','Stand hip-width apart and bend the knees enough for the hands to reach the floor safely.','Use fists or raise the hands for wrist discomfort; never force a painful stretch.','Take small hand steps; in the plank, head, trunk and pelvis stay aligned.','Complete 4 repetitions with bent knees and a brief plank.','Complete 6 slow repetitions, walking the hands out and feet forward in small steps.','Complete 8 repetitions with a stable plank and slightly longer reach.','Knees may stay bent; stop before the lower back sags.','Place hands on a bench and complete 4 short out-and-back walks.','Complete 6 floor repetitions with bent knees.','Complete 8 repetitions with straighter legs only while the back remains steady.','Use a short caterpillar walk on a clear mat; keep it slow and give each child room.','Raise hands on a stable surface and take only a few steps out.','Replace with an elevated wall plank and alternating shoulder taps.'
),('jumping-jacks','de','Hampelmänner koordinieren Arm- und Beinöffnung mit einem federnden, rhythmischen Sprung.','Erhöhen Puls und Ganzkörpertemperatur; die Landung wird weich gehalten und kann bei Bedarf ohne Sprung erfolgen.','Prüfe rutschfesten Boden und ausreichenden Seitenabstand; entferne Taschen und lose Hütchen.','Stehe aufrecht mit Füßen zusammen, Armen seitlich und Blick nach vorn.','Bei Gelenkschmerz, lauter harter Landung oder fehlendem Platz auf die Schrittvariante wechseln.','Leise auf dem Vorfuß-Mittelfußbereich landen, Knie folgen den Zehen und Arme bewegen sich ohne Schulterzwang.','2 x 20 Sekunden Step-Jacks ohne Sprung, dazwischen 20 Sekunden Pause.','3 x 20 Sekunden Hampelmänner mit 30 Sekunden Pause.','4 x 30 Sekunden im gleichmäßigen Rhythmus; nur solange Landungen leise bleiben.','Ohne Sprung ausführen, wenn die Landung nicht leise und stabil gelingt.','Step-Jack: einen Fuß seitlich setzen und Arme bis Schulterhöhe heben.','20 Sekunden rhythmische Hampelmänner, danach 30 Sekunden locker gehen.','30 Sekunden gleichmäßige Wiederholungen mit weicher Landung.','Musik-Stopp-Spiel mit Step-Jacks oder kleinen Sprüngen; Kinder wählen selbst die Variante.','Seitliches Tippen ohne Sprung und Arme nur bis zur angenehmen Höhe heben.','Durch zügiges Marschieren mit abwechselndem Armheben ersetzen.'
),('jumping-jacks','en','Jumping jacks coordinate opening the arms and legs with a light rhythmic jump.','Raises pulse and whole-body temperature; land softly and switch to a no-jump option when needed.','Check non-slip flooring and generous side spacing; move bags and loose cones away.','Stand tall with feet together, arms by the sides and eyes forward.','Switch to the step version for joint discomfort, loud hard landings or limited space.','Land quietly through the mid-foot, let knees track over toes and move arms without forcing the shoulders.','Complete 2 x 20 seconds of step jacks without jumping, resting 20 seconds.','Complete 3 x 20 seconds of jumping jacks with 30 seconds rest.','Complete 4 x 30 seconds at an even rhythm only while landings stay quiet.','Remove the jump whenever a quiet, stable landing is not consistent.','Step one foot sideways and lift arms to shoulder height, alternating sides.','Perform rhythmic jumping jacks for 20 seconds, then walk easily for 30 seconds.','Complete 30 seconds of even repetitions with soft landings.','Play a music-stop game using step jacks or small jumps; children choose their version.','Tap one foot sideways without jumping and lift arms only to a comfortable height.','Replace with brisk marching and alternating arm lifts.'
),('reaction-tag','de','Das Reaktions-Fangspiel trainiert Wahrnehmung, Antritt und Richtungswechsel in einem klar begrenzten Feld.','Verknüpft ein eindeutiges Signal mit kontrollierter Beschleunigung und Abbremsung; Fangdruck und Körperkontakt bleiben ausgeschlossen.','Markiere ein kleines rechteckiges Feld mit flachen Hütchen und erkläre Stopp, Aus und sichere Auslaufwege.','Verteile die Gruppe mit genügend Abstand; starte im Gehen und höre auf das vereinbarte Farb- oder Rufsignal.','Kein Schubsen, Greifen oder Blockieren; bei Sturz sofort Spiel stoppen und Feld freimachen.','Richtungswechsel erfolgen mit kurzen Schritten und kontrolliertem Bremsen; niemand läuft blind rückwärts.','4 x 20 Sekunden mit Gehen und einfachem Signal, je 40 Sekunden Pause.','5 x 30 Sekunden bei lockerem Tempo mit 30–45 Sekunden Pause.','6 x 30 Sekunden; nur eine Regel oder ein Signal gleichzeitig schwieriger machen.','Das Feld verkleinern statt Tempo zu erzwingen; Stoppsignal gilt jederzeit.','In Paaren auf ein Signal zur passenden Linie gehen statt laufen.','20 Sekunden locker reagieren und auf das Stoppzeichen sicher stehen.','30 Sekunden mit zwei bekannten Signalen und kontrolliertem Richtungswechsel.','Kooperative Farb-Suche: alle laufen zu einer Farbe; niemand scheidet aus oder wird berührt.','Auf ein Signal zur nahen Markierung gehen und dort anhalten.','Durch ein stehendes Reaktionsspiel mit Zeigen auf die passende Farbe ersetzen.'
),('reaction-tag','en','Reaction tag practises awareness, first steps and direction changes inside a clearly bounded area.','Links a clear cue to controlled acceleration and braking; chasing pressure and physical contact are excluded.','Mark a small rectangle with flat cones and explain stop, out-of-bounds and clear run-out routes.','Space athletes well apart; begin walking and respond to the agreed colour or verbal cue.','No pushing, grabbing or blocking; stop play after any fall and clear the area.','Change direction with short steps and controlled braking; no blind backward running.','Complete 4 x 20 seconds walking to a simple cue, resting 40 seconds.','Complete 5 x 30 seconds at easy pace with 30–45 seconds rest.','Complete 6 x 30 seconds; change only one rule or cue at a time.','Reduce the playing area rather than forcing speed; the stop cue always applies.','In pairs, walk to the matching line on a cue instead of running.','Respond easily for 20 seconds and stop safely on the signal.','Use two familiar cues for 30 seconds with controlled direction changes.','Cooperative colour search: everyone moves to a colour; nobody is tagged or eliminated.','Walk to a nearby marker on a cue and stop there.','Replace with a standing reaction game pointing to the matching colour.'
)) AS v(seed_key,locale,summary,purpose,setup,start_position,safety_notes,quality_criteria,beginner_prescription,standard_prescription,advanced_prescription,work_rest_guidance,level_1,level_2,level_3,child_youth_variant,prerequisites,fallback_exercise);

UPDATE exercise_translations AS t SET summary = g.summary
FROM exercises AS e, warmup_seed_enrichment AS g
WHERE g.seed_key=e.seed_key AND g.locale=t.locale AND t.exercise_id=e.id;

UPDATE exercise_details AS d SET
  purpose=g.purpose, setup=g.setup, start_position=g.start_position,
  safety_notes=g.safety_notes, quality_criteria=g.quality_criteria,
  beginner_prescription=g.beginner_prescription,
  standard_prescription=g.standard_prescription,
  advanced_prescription=g.advanced_prescription,
  work_rest_guidance=g.work_rest_guidance,
  level_1=g.level_1, level_2=g.standard_prescription, level_3=g.level_3,
  child_youth_variant=g.child_youth_variant, prerequisites=g.prerequisites,
  fallback_exercise=g.fallback_exercise
FROM exercises AS e, warmup_seed_enrichment AS g
WHERE g.seed_key=e.seed_key AND g.locale=d.locale AND d.exercise_id=e.id;

DELETE FROM exercise_execution_steps WHERE exercise_id IN (SELECT id FROM exercises WHERE seed_key IN (SELECT seed_key FROM warmup_seed_enrichment));
INSERT INTO exercise_execution_steps
SELECT e.id,g.locale,s.step_order,s.instruction
FROM warmup_seed_enrichment AS g JOIN exercises AS e ON e.seed_key=g.seed_key
JOIN (VALUES
('easy-jog','de',1,'Gehe eine Runde zügig und prüfe, ob der Weg frei ist.'),('easy-jog','de',2,'Trabe locker an; halte Arme und Hände entspannt.'),('easy-jog','de',3,'Laufe gleichmäßig und gehe zum Ende ruhig aus.'),
('easy-jog','en',1,'Walk one brisk lap and check that the route is clear.'),('easy-jog','en',2,'Begin an easy jog with relaxed arms and hands.'),('easy-jog','en',3,'Keep an even pace, then walk to cool the effort.'),
('walk-jog','de',1,'Gehe bis zum Startsignal in aufrechter Haltung.'),('walk-jog','de',2,'Wechsle auf das Signal in einen lockeren Trab.'),('walk-jog','de',3,'Kehre beim nächsten Signal ins Gehen zurück und atme ruhig.'),
('walk-jog','en',1,'Walk upright until the start signal.'),('walk-jog','en',2,'Change to an easy jog when signalled.'),('walk-jog','en',3,'Return to walking at the next cue and let breathing settle.'),
('high-knees','de',1,'Marschiere an und hebe das Knie nur so weit, wie der Oberkörper ruhig bleibt.'),('high-knees','de',2,'Setze den Fuß unter der Hüfte auf und wechsle die Seite.'),('high-knees','de',3,'Laufe bis zur Markierung und gehe auf dem Rückweg.'),
('high-knees','en',1,'March and lift the knee only as far as the torso stays quiet.'),('high-knees','en',2,'Place the foot under the hip and alternate sides.'),('high-knees','en',3,'Move to the marker and walk back.'),
('butt-kicks','de',1,'Beginne mit kleinen lockeren Laufschritten.'),('butt-kicks','de',2,'Lass die Ferse locker nach hinten schwingen, ohne sie hochzuziehen.'),('butt-kicks','de',3,'Halte den Rhythmus leicht und gehe am Ende aus.'),
('butt-kicks','en',1,'Begin with small, relaxed running steps.'),('butt-kicks','en',2,'Let the heel swing back without pulling it upward.'),('butt-kicks','en',3,'Keep the rhythm light and walk to a stop.'),
('side-shuffle','de',1,'Stelle dich seitlich und beuge Knie und Hüfte leicht.'),('side-shuffle','de',2,'Drücke dich seitlich ab; die Füße bleiben parallel.'),('side-shuffle','de',3,'Bremse vor der Linie mit kurzen Schritten und wechsle die Richtung.'),
('side-shuffle','en',1,'Face sideways and soften the knees and hips.'),('side-shuffle','en',2,'Push laterally while keeping the feet parallel.'),('side-shuffle','en',3,'Brake with short steps before the line and change direction.'),
('carioca','de',1,'Gehe seitlich und kreuze einen Fuß vor dem Standbein.'),('carioca','de',2,'Öffne den Schritt zur Seite und bleibe nach vorn ausgerichtet.'),('carioca','de',3,'Wiederhole klein und rhythmisch; halte vor dem Richtungswechsel an.'),
('carioca','en',1,'Travel sideways and cross one foot in front of the stance leg.'),('carioca','en',2,'Open the step to the side while keeping the torso forward.'),('carioca','en',3,'Repeat with small rhythmic steps and stop before changing direction.'),
('arm-circles','de',1,'Stelle dich stabil hin und hebe die Arme nur bis zur Wohlfühlhöhe.'),('arm-circles','de',2,'Kreise beide Arme klein nach vorn, ohne die Schultern hochzuziehen.'),('arm-circles','de',3,'Wechsle die Richtung und senke die Arme locker ab.'),
('arm-circles','en',1,'Stand steadily and lift the arms only to a comfortable height.'),('arm-circles','en',2,'Make small forward circles without shrugging.'),('arm-circles','en',3,'Reverse direction and lower the arms gently.'),
('inchworm','de',1,'Beuge Knie und Hüfte und setze die Hände vor den Füßen auf.'),('inchworm','de',2,'Wandere mit kleinen Hand-Schritten bis in einen stabilen Stütz.'),('inchworm','de',3,'Führe die Füße schrittweise nach und richte dich ohne Schwung auf.'),
('inchworm','en',1,'Bend the knees and hips and place hands in front of the feet.'),('inchworm','en',2,'Walk the hands forward in small steps to a steady plank.'),('inchworm','en',3,'Step the feet forward gradually and stand without momentum.'),
('jumping-jacks','de',1,'Springe oder steige die Füße seitlich auseinander und hebe die Arme.'),('jumping-jacks','de',2,'Kehre mit leiser Landung oder Seitstep zur Mitte zurück.'),('jumping-jacks','de',3,'Halte einen gleichmäßigen Takt und stoppe kontrolliert.'),
('jumping-jacks','en',1,'Jump or step the feet apart while lifting the arms.'),('jumping-jacks','en',2,'Return to the centre with a quiet landing or side step.'),('jumping-jacks','en',3,'Keep an even rhythm and stop under control.'),
('reaction-tag','de',1,'Bewege dich locker innerhalb der markierten Fläche.'),('reaction-tag','de',2,'Reagiere auf das Signal mit kurzen Schritten zur passenden Richtung.'),('reaction-tag','de',3,'Bremse vor der Begrenzung und bleibe beim Stoppsignal stehen.'),
('reaction-tag','en',1,'Move easily inside the marked area.'),('reaction-tag','en',2,'Respond to the cue with short steps in the matching direction.'),('reaction-tag','en',3,'Brake before the boundary and freeze on the stop cue.')
) AS s(seed_key,locale,step_order,instruction) ON s.seed_key=g.seed_key AND s.locale=g.locale;

DELETE FROM exercise_coaching_cues WHERE exercise_id IN (SELECT id FROM exercises WHERE seed_key IN (SELECT seed_key FROM warmup_seed_enrichment));
INSERT INTO exercise_coaching_cues
SELECT e.id,g.locale,c.cue_order,c.cue
FROM warmup_seed_enrichment AS g JOIN exercises AS e ON e.seed_key=g.seed_key
JOIN (VALUES
('easy-jog','de',1,'Sprechtempo halten'),('easy-jog','de',2,'Leise Schritte'),('easy-jog','en',1,'Keep conversational pace'),('easy-jog','en',2,'Quiet steps'),
('walk-jog','de',1,'Wechsel ohne Sprint'),('walk-jog','de',2,'Erholung zählt'),('walk-jog','en',1,'Change without sprinting'),('walk-jog','en',2,'Recovery counts'),
('high-knees','de',1,'Groß bleiben'),('high-knees','de',2,'Fuß unter die Hüfte'),('high-knees','en',1,'Stay tall'),('high-knees','en',2,'Foot under the hip'),
('butt-kicks','de',1,'Ferse locker zurück'),('butt-kicks','de',2,'Kleine Schritte'),('butt-kicks','en',1,'Relax the heel back'),('butt-kicks','en',2,'Keep steps small'),
('side-shuffle','de',1,'Füße parallel'),('side-shuffle','de',2,'Vor der Linie bremsen'),('side-shuffle','en',1,'Feet stay parallel'),('side-shuffle','en',2,'Brake before the line'),
('carioca','de',1,'Klein überkreuzen'),('carioca','de',2,'Erst Muster, dann Tempo'),('carioca','en',1,'Cross in small steps'),('carioca','en',2,'Pattern before pace'),
('arm-circles','de',1,'Nacken locker'),('arm-circles','de',2,'Kreis schmerzfrei'),('arm-circles','en',1,'Relax the neck'),('arm-circles','en',2,'Keep circles pain-free'),
('inchworm','de',1,'Rücken bleibt lang'),('inchworm','de',2,'Hände in kleinen Schritten'),('inchworm','en',1,'Keep the back long'),('inchworm','en',2,'Small hand steps'),
('jumping-jacks','de',1,'Leise landen'),('jumping-jacks','de',2,'Step-Variante ist okay'),('jumping-jacks','en',1,'Land softly'),('jumping-jacks','en',2,'Step version is fine'),
('reaction-tag','de',1,'Signal sehen, dann laufen'),('reaction-tag','de',2,'Vor der Linie stoppen'),('reaction-tag','en',1,'See the cue, then move'),('reaction-tag','en',2,'Stop before the line')
) AS c(seed_key,locale,cue_order,cue) ON c.seed_key=g.seed_key AND c.locale=g.locale;

DELETE FROM exercise_common_mistakes WHERE exercise_id IN (SELECT id FROM exercises WHERE seed_key IN (SELECT seed_key FROM warmup_seed_enrichment));
INSERT INTO exercise_common_mistakes
SELECT e.id,g.locale,m.mistake_order,m.mistake,m.correction
FROM warmup_seed_enrichment AS g JOIN exercises AS e ON e.seed_key=g.seed_key
JOIN (VALUES
('easy-jog','de',1,'Tempo steigt bis kein ganzer Satz mehr möglich ist.','Bis die Atmung ruhig ist gehen, dann langsamer wieder anlaufen.'),('easy-jog','en',1,'Pace rises until full sentences are no longer possible.','Walk until breathing settles, then resume more slowly.'),('easy-jog','de',2,'In der Kurve wird abrupt abgebremst.','Kurve weit laufen und die Geschwindigkeit schon vorher leicht reduzieren.'),('easy-jog','en',2,'The athlete brakes abruptly at the turn.','Take a wider turn and ease off before reaching it.'),
('walk-jog','de',1,'Der Laufabschnitt beginnt als Sprint.','Mit kleinen Schritten anlaufen und das Gesprächstempo einhalten.'),('walk-jog','en',1,'The jogging interval starts as a sprint.','Start with short steps and stay at conversational effort.'),('walk-jog','de',2,'Beim Wechsel bleibt der Oberkörper angespannt.','Beim Gehen die Arme lockern und vollständig ausatmen.'),('walk-jog','en',2,'The torso stays tense during the walking recovery.','Relax the arms and let a full exhale out while walking.'),
('high-knees','de',1,'Der Oberkörper lehnt sich bei jedem Kniehub zurück.','Knie niedriger heben und Rippen über dem Becken halten.'),('high-knees','en',1,'The torso leans backward with each knee drive.','Lower the knee and stack the ribs over the pelvis.'),('high-knees','de',2,'Die Füße landen weit vor dem Körper.','Schritt verkürzen und den Fuß unter der Hüfte aufsetzen.'),('high-knees','en',2,'Feet land far in front of the body.','Shorten the stride and land beneath the hip.'),
('butt-kicks','de',1,'Die Ferse wird mit der Hand zum Gesäß gezogen.','Arme natürlich mitschwingen lassen und die Ferse frei zurückpendeln.'),('butt-kicks','en',1,'The heel is pulled to the glute by the hand.','Let the arms swing naturally and allow the heel to recover freely.'),('butt-kicks','de',2,'Der Schritt wird laut und schwer.','Tempo drosseln und auf federleichten Fußaufsatz achten.'),('butt-kicks','en',2,'Steps become loud and heavy.','Slow down and aim for a light foot strike.'),
('side-shuffle','de',1,'Die Füße kreuzen und verhaken sich.','Schrittweite verringern und beide Füße parallel halten.'),('side-shuffle','en',1,'Feet cross and tangle.','Shorten the step and keep both feet parallel.'),('side-shuffle','de',2,'Vor der Linie erfolgt ein harter Sprungstopp.','Zwei bis drei kleinere Bremsschritte vor der Linie setzen.'),('side-shuffle','en',2,'A hard jump-stop occurs at the line.','Use two or three shorter braking steps before the line.'),
('carioca','de',1,'Der Oberkörper dreht vollständig zur Laufrichtung.','Kreuzschritt verkleinern und Brustkorb wieder nach vorn ausrichten.'),('carioca','en',1,'The whole torso turns toward the direction of travel.','Make the crossing step smaller and face the chest forward again.'),('carioca','de',2,'Die Füße überkreuzen sich zu weit und Gleichgewicht geht verloren.','Bewegung im Gehen üben und nur knapp vor dem Standbein kreuzen.'),('carioca','en',2,'Feet cross too far and balance is lost.','Practise at a walk and cross only just in front of the stance leg.'),
('arm-circles','de',1,'Der Rücken weicht ins Hohlkreuz aus.','Arme tiefer halten und Rippen über dem Becken stapeln.'),('arm-circles','en',1,'The back arches to compensate.','Lower the arms and stack ribs over the pelvis.'),('arm-circles','de',2,'Die Schultern wandern zu den Ohren.','Kreise kleiner machen und den Nacken lang lassen.'),('arm-circles','en',2,'Shoulders creep up toward the ears.','Reduce the circle and keep the neck long.'),
('inchworm','de',1,'Das Becken sinkt im Stütz zum Boden.','Knie beugen oder Hände erhöht aufsetzen, bis Kopf und Becken eine Linie bilden.'),('inchworm','en',1,'The pelvis sags in the plank.','Bend the knees or raise the hands until head and pelvis align.'),('inchworm','de',2,'Die Hände werden weit nach vorn gesetzt und der Rücken hängt durch.','Kürzere Hand-Schritte gehen und die Stützposition vor dem Umkehren prüfen.'),('inchworm','en',2,'Hands reach too far and the back sags.','Take shorter hand steps and check the plank before returning.'),
('jumping-jacks','de',1,'Die Landung ist laut und die Knie fallen nach innen.','Zur Step-Variante wechseln und Knie über den Zehen ausrichten.'),('jumping-jacks','en',1,'Landing is loud and knees collapse inward.','Switch to step jacks and align knees over the toes.'),('jumping-jacks','de',2,'Die Arme werden trotz Schulterspannung über Kopf gezwungen.','Arme nur bis zur angenehmen Höhe heben.'),('jumping-jacks','en',2,'Arms are forced overhead despite shoulder tension.','Lift the arms only to a comfortable height.'),
('reaction-tag','de',1,'Alle starten gleichzeitig und laufen in dieselbe Lücke.','Einzelne Startgruppen bilden und Fluchtwege vor jeder Runde festlegen.'),('reaction-tag','en',1,'Everyone starts together and crowds the same gap.','Stagger starts and identify clear routes before each round.'),('reaction-tag','de',2,'Spieler schauen beim Richtungswechsel nur auf andere.','Kopf heben, freie Fläche wählen und das Tempo reduzieren.'),('reaction-tag','en',2,'Players look only at others during direction changes.','Lift the head, choose open space and reduce speed.')
) AS m(seed_key,locale,mistake_order,mistake,correction) ON m.seed_key=g.seed_key AND m.locale=g.locale;

UPDATE exercises SET
  exercise_type='drill',
  impact_level=CASE WHEN seed_key IN ('jumping-jacks','high-knees','butt-kicks','carioca','side-shuffle') THEN 'moderate' ELSE 'low' END,
  coordination_complexity=CASE WHEN seed_key IN ('reaction-tag','carioca','side-shuffle') THEN 'moderate' ELSE 'simple' END,
  supports_reps=false,supports_seconds=true,supports_minutes=true,supports_metres=true,
  supports_rounds=true,supports_attempts=false,
  station_capacity=CASE WHEN seed_key='reaction-tag' THEN 12 ELSE 1 END
WHERE seed_key IN (SELECT seed_key FROM warmup_seed_enrichment);

DELETE FROM exercise_body_regions WHERE exercise_id IN (SELECT id FROM exercises WHERE seed_key IN (SELECT seed_key FROM warmup_seed_enrichment));
INSERT INTO exercise_body_regions (exercise_id,body_region_id,emphasis)
SELECT e.id,m.body_region_id,m.emphasis
FROM exercises e JOIN (VALUES
('easy-jog','full-body','primary'),('walk-jog','full-body','primary'),('high-knees','quadriceps','primary'),('high-knees','calves','secondary'),
('butt-kicks','hamstrings','primary'),('butt-kicks','calves','secondary'),('side-shuffle','adductors','primary'),('side-shuffle','glutes','secondary'),
('carioca','hips','primary'),('carioca','adductors','secondary'),('arm-circles','shoulders','primary'),('arm-circles','upper-back','secondary'),
('inchworm','full-body','primary'),('inchworm','shoulders','secondary'),('jumping-jacks','full-body','primary'),('reaction-tag','full-body','primary')
) AS m(seed_key,body_region_id,emphasis) ON m.seed_key=e.seed_key;

DELETE FROM exercise_movement_patterns WHERE exercise_id IN (SELECT id FROM exercises WHERE seed_key IN (SELECT seed_key FROM warmup_seed_enrichment));
INSERT INTO exercise_movement_patterns (exercise_id,movement_pattern_id)
SELECT e.id,m.movement_pattern_id
FROM exercises e JOIN (VALUES
('easy-jog','run'),('walk-jog','run'),('walk-jog','walk'),('high-knees','run'),('butt-kicks','run'),('side-shuffle','agility'),
('carioca','agility'),('carioca','rotate'),('arm-circles','mobility'),('inchworm','brace'),('inchworm','mobility'),
('jumping-jacks','jump'),('jumping-jacks','land'),('reaction-tag','agility'),('reaction-tag','run')
) AS m(seed_key,movement_pattern_id) ON m.seed_key=e.seed_key;

UPDATE search_documents_de AS s SET
  summary=t.summary,
  instructions=d.purpose || ' ' || d.setup || ' ' || d.start_position || ' ' || d.safety_notes || ' ' || d.quality_criteria || ' ' || COALESCE((SELECT string_agg(x.instruction,' ') FROM exercise_execution_steps x WHERE x.exercise_id=e.id AND x.locale='de'),'')
FROM exercises e, exercise_translations t, exercise_details d
WHERE e.seed_key IN (SELECT seed_key FROM warmup_seed_enrichment) AND t.exercise_id=e.id AND t.locale='de' AND d.exercise_id=e.id AND d.locale='de' AND s.entity_id=e.id::VARCHAR;

UPDATE search_documents_en AS s SET
  summary=t.summary,
  instructions=d.purpose || ' ' || d.setup || ' ' || d.start_position || ' ' || d.safety_notes || ' ' || d.quality_criteria || ' ' || COALESCE((SELECT string_agg(x.instruction,' ') FROM exercise_execution_steps x WHERE x.exercise_id=e.id AND x.locale='en'),'')
FROM exercises e, exercise_translations t, exercise_details d
WHERE e.seed_key IN (SELECT seed_key FROM warmup_seed_enrichment) AND t.exercise_id=e.id AND t.locale='en' AND d.exercise_id=e.id AND d.locale='en' AND s.entity_id=e.id::VARCHAR;

INSERT INTO schema_migrations (version,name) VALUES (9,'warmup_seed_enrichment');
DROP TABLE warmup_seed_enrichment;
COMMIT;
