-- Derived catalog from vulovix/body-muscles; see vendor/body-muscles/NOTICE.
BEGIN TRANSACTION;
INSERT OR IGNORE INTO body_regions (id,label_de,label_en) VALUES
('detail:head','Kopf (Körperbereich)','Head'),
('detail:face','Gesicht (Körperbereich)','Face'),
('detail:neck-right','Halsmuskulatur · rechts','Right Neck'),
('detail:neck-left','Halsmuskulatur · links','Left Neck'),
('detail:shoulder-front-left','Vordere Schulter · links','Left Shoulder (Front)'),
('detail:shoulder-side-left','Seitliche Schulter · links','Left Shoulder (Side)'),
('detail:shoulder-front-right','Vordere Schulter · rechts','Right Shoulder (Front)'),
('detail:shoulder-side-right','Seitliche Schulter · rechts','Right Shoulder (Side)'),
('detail:biceps-left','Bizeps · links','Left Biceps'),
('detail:forearm-left','Unterarm · links','Left Forearm'),
('detail:biceps-right','Bizeps · rechts','Right Biceps'),
('detail:forearm-right','Unterarm · rechts','Right Forearm'),
('detail:chest-upper-left','Brust · oberer Anteil · links','Left Upper Chest (Clavicular)'),
('detail:chest-lower-left','Brust · unterer Anteil · links','Left Lower Chest (Sternal)'),
('detail:chest-upper-right','Brust · oberer Anteil · rechts','Right Upper Chest (Clavicular)'),
('detail:chest-lower-right','Brust · unterer Anteil · rechts','Right Lower Chest (Sternal)'),
('detail:abs-upper-left','Bauch · oberer Anteil · links','Left Abs (Upper)'),
('detail:serratus-anterior-left','Vorderer Sägemuskel · links','Left Serratus Anterior'),
('detail:obliques-left','Äußere schräge Bauchmuskeln · links','Left External Oblique'),
('detail:abs-upper-right','Bauch · oberer Anteil · rechts','Right Abs (Upper)'),
('detail:abs-lower-right','Bauch · unterer Anteil · rechts','Right Lower Abs'),
('detail:abs-lower-left','Bauch · unterer Anteil · links','Left Lower Abs'),
('detail:serratus-anterior-right','Vorderer Sägemuskel · rechts','Right Serratus Anterior'),
('detail:obliques-right','Äußere schräge Bauchmuskeln · rechts','Right External Oblique'),
('detail:hip-flexor-right','Hüftbeuger / Leiste · rechts','Right Groin / Hip Flexors'),
('detail:hip-flexor-left','Hüftbeuger / Leiste · links','Left Groin / Hip Flexors'),
('detail:quads-left','Quadrizeps · links','Left Quadriceps'),
('detail:adductors-left','Adduktoren · links','Left Adductors'),
('detail:foot-left','Fuß / Sprunggelenk · links','Left Foot'),
('detail:tibialis-anterior-left','Vorderer Schienbeinmuskel · links','Left Tibialis Anterior'),
('detail:knee-left','Knie (Gelenk) · links','Left Knee'),
('detail:quads-right','Quadrizeps · rechts','Right Quadriceps'),
('detail:adductors-right','Adduktoren · rechts','Right Adductors'),
('detail:foot-right','Fuß / Sprunggelenk · rechts','Right Foot'),
('detail:tibialis-anterior-right','Vorderer Schienbeinmuskel · rechts','Right Tibialis Anterior'),
('detail:knee-right','Knie (Gelenk) · rechts','Right Knee'),
('detail:elbow-right','Ellenbogen (Gelenk) · rechts','Right Elbow'),
('detail:hand-right','Hand / Finger · rechts','Right Hand'),
('detail:elbow-left','Ellenbogen (Gelenk) · links','Left Elbow'),
('detail:hand-left','Hand / Finger · links','Left Hand'),
('detail:head-back','Hinterkopf (Körperbereich)','Head (Posterior)'),
('detail:nape','Nacken','Nape'),
('detail:traps-upper-left','Trapez · oberer Anteil · links','Left Trapezius (Upper)'),
('detail:traps-mid-left','Trapez · mittlerer Anteil · links','Left Trapezius (Mid)'),
('detail:traps-lower-left','Trapez · unterer Anteil · links','Left Trapezius (Lower)'),
('detail:traps-upper-right','Trapez · oberer Anteil · rechts','Right Trapezius (Upper)'),
('detail:traps-mid-right','Trapez · mittlerer Anteil · rechts','Right Trapezius (Mid)'),
('detail:traps-lower-right','Trapez · unterer Anteil · rechts','Right Trapezius (Lower)'),
('detail:lats-upper-left','Latissimus · oberer Anteil · links','Left Lats (Upper)'),
('detail:deltoid-rear-left','Hintere Schulter · links','Left Rear Deltoid'),
('detail:lats-mid-left','Latissimus · mittlerer Anteil · links','Left Lats (Mid)'),
('detail:lats-lower-left','Latissimus · unterer Anteil · links','Left Lats (Lower)'),
('detail:deltoid-rear-right','Hintere Schulter · rechts','Right Rear Deltoid'),
('detail:lats-upper-right','Latissimus · oberer Anteil · rechts','Right Lats (Upper)'),
('detail:lats-mid-right','Latissimus · mittlerer Anteil · rechts','Right Lats (Mid)'),
('detail:lats-lower-right','Latissimus · unterer Anteil · rechts','Right Lats (Lower)'),
('detail:triceps-long-left','Trizeps · langer Kopf · links','Left Triceps (Long Head)'),
('detail:triceps-lateral-left','Trizeps · äußerer Kopf · links','Left Triceps (Lateral Head)'),
('detail:hand-back-left','Handrücken / Finger · links','Left Hand (Back)'),
('detail:forearm-flexors-left','Unterarmbeuger · links','Forearm Flexors Left'),
('detail:forearm-extensors-left','Unterarmstrecker · links','Forearm Extensors Left'),
('detail:triceps-long-right','Trizeps · langer Kopf · rechts','Right Triceps (Long Head)'),
('detail:triceps-lateral-right','Trizeps · äußerer Kopf · rechts','Right Triceps (Lateral Head)'),
('detail:hand-back-right','Handrücken / Finger · rechts','Right Hand (Back)'),
('detail:forearm-flexors-right','Unterarmbeuger · rechts','Forearm Flexors Right'),
('detail:forearm-extensors-right','Unterarmstrecker · rechts','Forearm Extensors Right'),
('detail:spine','Wirbelsäule (Körperbereich)','Spine'),
('detail:lower-back-erectors-left','Rückenstrecker · links','Erector Spinae Left'),
('detail:lower-back-ql-left','Quadratischer Lendenmuskel · links','Quadratus Lumborum Left'),
('detail:lower-back-erectors-right','Rückenstrecker · rechts','Erector Spinae Right'),
('detail:lower-back-ql-right','Quadratischer Lendenmuskel · rechts','Quadratus Lumborum Right'),
('detail:gluteus-medius-left','Mittlerer Gesäßmuskel · links','Gluteus Medius Left'),
('detail:gluteus-maximus-left','Großer Gesäßmuskel · links','Gluteus Maximus Left'),
('detail:gluteus-medius-right','Mittlerer Gesäßmuskel · rechts','Gluteus Medius Right'),
('detail:gluteus-maximus-right','Großer Gesäßmuskel · rechts','Gluteus Maximus Right'),
('detail:knee-back-left','Kniekehle (Gelenk) · links','Left Back Knee'),
('detail:knee-back-right','Kniekehle (Gelenk) · rechts','Right Back Knee'),
('detail:calves-gastroc-medial-left','Zwillingswade · innerer Kopf · links','Gastrocnemius Medial Left'),
('detail:calves-gastroc-lateral-left','Zwillingswade · äußerer Kopf · links','Gastrocnemius Lateral Left'),
('detail:calves-soleus-left','Schollenmuskel · links','Soleus Left'),
('detail:calves-gastroc-medial-right','Zwillingswade · innerer Kopf · rechts','Gastrocnemius Medial Right'),
('detail:calves-gastroc-lateral-right','Zwillingswade · äußerer Kopf · rechts','Gastrocnemius Lateral Right'),
('detail:calves-soleus-right','Schollenmuskel · rechts','Soleus Right'),
('detail:foot-back-left','Fuß / Ferse · links','Left Foot (Back)'),
('detail:hamstrings-medial-left','Hamstrings · innere Anteile · links','Medial Hamstrings (Semis) Left'),
('detail:hamstrings-lateral-left','Hamstrings · äußerer Anteil · links','Lateral Hamstrings (Biceps) Left'),
('detail:foot-back-right','Fuß / Ferse · rechts','Right Foot (Back)'),
('detail:hamstrings-medial-right','Hamstrings · innere Anteile · rechts','Medial Hamstrings (Semis) Right'),
('detail:hamstrings-lateral-right','Hamstrings · äußerer Anteil · rechts','Lateral Hamstrings (Biceps) Right');
INSERT OR IGNORE INTO schema_migrations (version,name) VALUES (22,'detailed_body_regions');
COMMIT;
